### ISSUE TITLE
go.skimresources.com - false positive

### ISSUE THREAD

**Issue by git-anish** [anudeepND/blacklist#101]
Hey,

go.skimresources.com

is a false positive, if blocked it will block affiliate links from websites like redflagdeals.com

Regards,

Anish S

**Comment by git-anish** [comment]
this might also be the case for other skimresources.com URLs but i'm not sure

I've only tested go.skimresources.com

**Comment by anudeepND** [comment]
@git-anish They track users using invisible pixels. perform behavioral analysis and targeted advertising. For more information take a look at: 
https://better.fyi/trackers/skimresources.com/
https://whotracks.me/trackers/skimlinks.html/

They operate under different domains such as redirectingat.com and skimlinks.com, currently they're not present in the list. I will add them in the future updates
