### ISSUE TITLE
should "ads.twitter.com" be on here?

### ISSUE THREAD

**Issue by petersmagnusson** [anudeepND/blacklist#102]
blocking it means blocking Twitter dashboards etc.  is this domain used in other ways?  i don't think it's used to deliver ads other than if you're on twitter (or?).

**Comment by anudeepND** [comment]
@petersmagnusson It is blocked on almost all host files. However after looking at the documentation I couldn't find any code that includes `ads.twitter.com`. I will remove it in the next update
