### ISSUE TITLE
Consider whitelisting *.trafficdeposit.com

### ISSUE THREAD

**Issue by FBN7nbF4t7e2Y** [anudeepND/blacklist#103]
Traffic Deposit is like a CDN for porn. I’m sure it has Ads on it, but it has other videos too. For example, blocking it breaks all the free videos on the porn site: sxyprn.com

Please whitelist it.

**Comment by anudeepND** [comment]
@FBN7nbF4t7e2Y Thanks for reporting. Removed in the latest update
