### ISSUE TITLE
New Domain you should add to the list

### ISSUE THREAD

**Issue by MrWaste** [anudeepND/blacklist#105]
Everything in this list should be blocked :)
Sorry for the huge list, I have a full lists I create from scratch. I do have alot more if you want them!!
If I could help out here that would be great like a contributor. 

img.img-taboola.com
I had this one pop up a month ago for some reason and after blacklisting it, no problems with websites.

ascstats.iobit.com
Proof:
https://threatintelligenceplatform.com/report/ascstats.iobit.com/hjPkIXXTgo

https://any.run/report/059ae460d80e8beec1aff079b966608f239c5d7cdc6b43488c49d2291e9a9b04/aca9aedc-ba5f-46dc-80ee-4827996aaa5a
This one is with iobit.com, Advanced system care.

p3a.brave.com
https://brave.com/privacy-preserving-product-analytics-p3a/
You should block.

analytics-query-atsv2.g03.yahoodns.net
Proof:
https://threatintelligenceplatform.com/report/analytics-query-atsv2.g03.yahoodns.net/yQAPOmItHS

any-ycpi-uno.aycpi.b.yahoodns.net
any-ycpi-uno-lite.aycpi.b.yahoodns.net
These two are the Main infrastructure servers domains. You should block. with analytics-query-atsv2.g03.yahoodns.net

https://threatintelligenceplatform.com/report/analytics-query-atsv2.g03.yahoodns.net/yQAPOmItHS

While researching these I found even more with the last 3 already

dataxtoplevel.data.g01.yahoodns.net
ds-any-ycpi-uno.aycpi.b.yahoodns.net
fam-geo-atsv2.prod.media.g03.yahoodns.net
ds-geoycpi-uno-deluxe.gycpi.b.yahoodns.net

These two I found somewhere with the rest of them from the top, they aren't good.
ycpi-prod4cws.xobni.g03.yahoodns.net
https://threatintelligenceplatform.com/report/ycpi-prod4cws.xobni.g03.yahoodns.net/se3uNAi9dR
ycpi-data.xobni.g01.yahoodns.net
https://threatintelligenceplatform.com/report/ycpi-data.xobni.g01.yahoodns.net/T8AZQkpQi3

Here's More, all these should be blocked, really look at them..
f-log-extension.grammarly.io
data.grammarly.com
statics-marketingsites-neu-ms-com.akamaized.net
statics-marketingsites-wcus-ms-com.akamaized.net
statics-marketingsites-eas-ms-com.akamaized.net
co4.telecommand.telemetry.microsoft.com.akadns.net
datanyze-logos.s3.amazonaws.com
wyze-datacollect-api.wyzecam.com

improving.duckduckgo.com
https://help.duckduckgo.com/duckduckgo-help-pages/privacy/atb/

Same thing as: 
uphold.report-uri.com
report-uri.com
Should both be blocked
Proof:
https://www.google.com/search?q=what+is+report-uri.com&oq=what+is+report-uri.com&aqs=chrome..69i57j0.1953j0j1&sourceid=chrome&ie=UTF-8

data.ripple.com
Proof:
https://data.ripple.com/

uofmresearch.isr.umich.edu
This one should really be blocked if your firewall is down they ping this request to your dns server.

version.bind
Please block this!!
Proof:
https://kb.isc.org/docs/aa-00359
Not a good idea..
https://www.reddit.com/r/pihole/comments/aeyjvf/versionbind_issues/

log.mangaina.com
logs.x1.com
firebaseinstallations.googleapis.com
marketing-tii-statamic-assets-ca-central-1.s3.ca-central-1.amazonaws.com

ksn-stat-geo.kaspersky-labs.com
https://support.kaspersky.com/12400
This is not in the list link and pings way to much on you and more than likely is collecting data on you, has been block for 1 year and no problems ever.

prod.telemetry.ros.rockstargames.com
https://www.unknowncheats.me/forum/grand-theft-auto-v/230381-stop-game-sending-info-regarding-modding.html?__cf_chl_jschl_tk__=2db645435b5b013d3eb4f5bd3784b0bcff58fcad-1589080929-0-AXV9GoDXjvavHo4d9cElB436VmrGlfkDHZ7Il8aCIDxKPFo61kA4cAJyep-HFvrgtpBNpRzJpVRocfjqWhG5CSqBMZ3qTVjFQIAajF9_L0IHvvbVbHi5fZFalmfXfDGLveU04FH37i-gqdAs9OCmMU-n6c06iaZw7fNFROd0SrNIK7uf-Li2ewYvEHEytQEqK_J1zu1IQ8hRCDkbLPblQPY7bJgUZHtI-wtBXyHNmfSLwd70JuxU5lZpbANhPyCXSW-8I_aSMw68izO_P2fyxTqMMP4RRhPingD3_Adihku5S-ZWsAaKQI3rfoAHAuCu0CvTFASWdffJC7jUYHPhzpAng-0_61l7ailQoQSz3toVmlukWsUHWktvKi-O-s8uFA
Read the first post ONLY if you want.

setting-logncrash.cloud.toast.com
Proof:
https://threatintelligenceplatform.com/report/setting-logncrash.cloud.toast.com/SIWSfeZYdB
Main Infrastructures Servers: 
logncrash.slb.toastoven.net

s.ispoofer.com
don't block: www.ispoofer.com 
That's the website but if you use the cheat all the data go to the domain s.ispoofer.com
https://www.ispoofer.com/#
The cheat works while blocking it and its just your location data they are collecting on you. Not good and the only way you can remove it by paying for the full version to disable that feature.

List Form:
img.img-taboola.com
ascstats.iobit.com
p3a.brave.com
analytics-query-atsv2.g03.yahoodns.net
any-ycpi-uno.aycpi.b.yahoodns.net
any-ycpi-uno-lite.aycpi.b.yahoodns.net
atsv2.g03.yahoodns.net
dataxtoplevel.data.g01.yahoodns.net
ds-any-ycpi-uno.aycpi.b.yahoodns.net
fam-geo-atsv2.prod.media.g03.yahoodns.net
ds-geoycpi-uno-deluxe.gycpi.b.yahoodns.net
ycpi-prod4cws.xobni.g03.yahoodns.net
ycpi-data.xobni.g01.yahoodns.net
f-log-extension.grammarly.io
data.grammarly.com
statics-marketingsites-neu-ms-com.akamaized.net
statics-marketingsites-wcus-ms-com.akamaized.net
statics-marketingsites-eas-ms-com.akamaized.net
co4.telecommand.telemetry.microsoft.com.akadns.net
datanyze-logos.s3.amazonaws.com
wyze-datacollect-api.wyzecam.com
improving.duckduckgo.com
uphold.report-uri.com
report-uri.com
data.ripple.com
uofmresearch.isr.umich.edu
version.bind
prod.telemetry.ros.rockstargames.com
setting-logncrash.cloud.toast.com
logncrash.slb.toastoven.net
s.ispoofer.com

Good Luck

**Comment by beerisgood** [comment]
report-uri.com is a legit site

**Comment by MrWaste** [comment]
Ok, but how come is it in a different list? The top list, I have been looking and it doesn't seem 

Proof:

![34](https://user-images.githubusercontent.com/49108816/81508726-b7983780-92ba-11ea-962f-9c6e754903ac.png)

![35](https://user-images.githubusercontent.com/49108816/81508776-0776fe80-92bb-11ea-922b-14e7dd2f64f7.png)

You go to the site and look at it.

https://report-uri.com/

**Comment by llacb47** [comment]
`version.bind`

?

**Comment by spirillen** [comment]
Hmm you are talking about privacy protecting submissions, yet you are linking to the worst spyware/adware/trackware/privacy invasive domain out there... `google.com`!! 

Beside of that, you have some good submissions. I would look at to my list. Thanks for those :smiley: :beer:

**Comment by beerisgood** [comment]
> Ok, but how come is it in a different list? The top list, I have been looking and it doesn't seem any good, only reports things.
> 
> Proof:
> 
> ![34](https://user-images.githubusercontent.com/49108816/81508726-b7983780-92ba-11ea-962f-9c6e754903ac.png)
> 
> ![35](https://user-images.githubusercontent.com/49108816/81508776-0776fe80-92bb-11ea-922b-14e7dd2f64f7.png)
> 
> You go to the site and look at it.
> 
> https://report-uri.com/

It's a server side service which don't need to be blocked.
Also I don't know your posted 2 "top" lists. This is just a false positive and I don't see it on many other filterlists

**Comment by MrWaste** [comment]
beerisgood,

The reason why you don't see ascstats.iobit.com because you haven't installed Advanced System Care on your system. When you have the requests start to go through.
[Click Here, Website](https://www.iobit.com/en/advancedsystemcarefree.php)

**Comment by MrWaste** [comment]
> Hmm you are talking about privacy protecting submissions, yet you are linking to the worst spyware/adware/trackware/privacy invasive domain out there... `google.com`!!
> 
> Beside of that, you have some good submissions. I would look at to my list. Thanks for those 😃 🍺

spirillen,

When you said "I would look at to my list." do you mean I would look to add to my list? or something else?

**Comment by MrWaste** [comment]
> `version.bind`
> 
> ?

llacb47,

version.bind has vulnerabilities built into itself if you have no firewall up for port 53/dns traffic.

[version.bind Link](https://kb.isc.org/docs/aa-00913)

**Comment by spirillen** [comment]
> > Hmm you are talking about privacy protecting submissions, yet you are linking to the worst spyware/adware/trackware/privacy invasive domain out there... `google.com`!!
> > Beside of that, you have some good submissions. I would look at to my list. Thanks for those smiley beer
> 
> spirillen,
> 
> When you said "I would look at to my list." do you mean I would look to add to my list? or something else?

my list = <https://www.mypdns.org/source/Matrix/>

**Comment by MrWaste** [comment]
oh ok

**Comment by anudeepND** [comment]
Sorry for the late reply everyone. I will take a look at the info provided and add it the next update.

**Comment by spirillen** [comment]
> beerisgood,
> 
> The reason why you don't see ascstats.iobit.com because you haven't installed Advanced System Care on your system. When you have it installed the requests start to go through.
> [Click Here, Website](https://www.iobit.com/en/advancedsystemcarefree.php)

@MrWaste Do you have any deeper details of why you think `ascstats.iobit.com` should go into any block-lists?

The name itself suggest tracking, but what does it do?

Have you tried to block it for a longer periods of time? IF == yes, what happens?
  - I do not see any usefully information for why this should be blocked on there website nor there privacy policy, the harvester is yet again google..

**Comment by anudeepND** [comment]
I have added few domains, I will add others after some testing
