### ISSUE TITLE
code.ionicframework.com FP?

### ISSUE THREAD

**Issue by XhmikosR** [anudeepND/blacklist#108]
Hi, there.

I was wondering, what's the reason for blocking code.ionicframework.com?

Thanks!

**Comment by anudeepND** [comment]
@XhmikosR it was added by mistake. Will be removed in the next update.

**Comment by anudeepND** [comment]
Fixed in. https://github.com/anudeepND/blacklist/commit/d6e6b629a6e4a7d9abb6d6b5fd35e22c69e05fb7. Closing
