### ISSUE TITLE
False positive - schibsted.com

### ISSUE THREAD

**Issue by zappe** [anudeepND/blacklist#109]
This is a company website

**Comment by anudeepND** [comment]
@zappe sorry for the late reply. It will be removed in the next update

**Comment by spirillen** [comment]
https://sdk.pulse.schibsted.com/#tracking-guide

https://whotracks.me/trackers/schibsted.html

**Comment by anudeepND** [comment]
@spirillen Thanks for the links. It's a tracker, it will not be removed.

**Comment by spirillen** [comment]
NP, I had them in my own issue for the $domain :smiley:
