### ISSUE TITLE
Forms/surveys on Qualtrics domains

### ISSUE THREAD

**Issue by ACMEd** [anudeepND/blacklist#110]
Take a look at lightswitch05/hosts#178.
Although Qualtrics is an analytics company, many `*.qualtrics.com` sub domains are used for forms and surveys.

**Comment by anudeepND** [comment]
@ACMEd thanks for reporting. Will be removed in the next update.

**Comment by anudeepND** [comment]
@ACMEd I have removed `*.qualtrics.com` domains, only necessary domains will remain in the list
