### ISSUE TITLE
statics.streamable.com

### ISSUE THREAD

**Issue by TheNoobWar** [anudeepND/blacklist#111]
`statics.streamable.com` is a false-positive. It will not display streamable.com webpage, a low-bloat video hosting platform.

**Comment by spirillen** [comment]
[streamable.com](https://www.mypdns.org/T926) is no more than google/youtube, we try to simulate we are serving videos, but in reality we are trackware....

**Comment by PureFallen** [comment]
`statics.streamable.com` is a bit tricky. While it is possible to watch shared videos submitted over `streamable.com` when the domain is blacklisted, the website itself seems to be delivered from `statics.streamable.com`, including the actual UI around the video and the ability to upload new ones.
While @spirillen ´s concern is completely reasonable, the whole situation puts us on the conflict of either:

- Keeping `statics.streamable.com` blacklisted and take users the ability to upload content in exchange for enhanced privacy in case the tracking happens over this domain.
- Removing `statics.streamable.com` and give users the ability to upload content and use accounts on the website again, playing with the price of privacy if the tracking is done over this domain.

What speaks for keeping it in the blacklist it, that most people will use streamable as viewer, not as uploader. What speaks against it is, that a good blacklist should not handycap the user´s ability to use the website or cut features. At this point it is probably @anudeepND ´s decision.

**Comment by spirillen** [comment]
> What speaks against it is, that a good blacklist should not handycap the user´s ability to use the website or cut features

 I would defiantly like to dispute that :smile: 

A god blacklist should protect users against this, even if the webdesigner have broken the frontend by adding spyware tp the site. <https://www.mypdns.org/source/Matrix/browse/master/README.md$39>

**Comment by PureFallen** [comment]
> A god blacklist should protect users against this, even if the webdesigner have broken the frontend by adding spyware tp the site. https://www.mypdns.org/source/Matrix/browse/master/README.md$39

If we would go with that approach, we would probably need to go ahead and wildcard several Google Websites as well. Yes - it would probably be the better approach to not use them in first place, but that doesn't prevent others from doing so.
I don't really care about the Website UI, more of the Upload Functionality that is affected by that block. Not that streamable.com gonna complain at some point...
Anyway, i don't know myself if it should be blocked or not. Dropped my 2 cents and the context i have, at the end it's not in my power to decide that.

**Comment by llacb47** [comment]
`What did we write in the previous answer? Are you stupid?` (https://www.mypdns.org/source/Matrix/browse/master/README.md$39)

@spirillen feel free to email every website here and tell them that they are stupid. https://publicwww.com/websites/%22googleapis.com%22/ I'm sure they will appreciate it. Like it or not, millions or websites use third-party assets for convenience and speed. Calling them stupid isn't helping.

**Comment by spirillen** [comment]
Hey @PureFallen Thanks for your point and good tone to the debate and argumentation :+1:

**Comment by anudeepND** [comment]
@TheNoobWar can you please provide me some screenshots? Does the video playback works fine? streamable.com is blocked by my ISP :(
