### ISSUE TITLE
s-media-cache-ak0.pinimg.com potential false positive

### ISSUE THREAD

**Issue by mkb2091** [anudeepND/blacklist#114]
s-media-cache-ak0.pinimg.com blocks access to https://s-media-cache-ak0.pinimg.com/originals/28/86/42/288642dec69cb52611e17a2afadc940e.jpg. That url is redirects to https://i.pinimg.com/originals/28/86/42/288642dec69cb52611e17a2afadc940e.jpg which isn't blocked, and, is an image from a video game. 

The original url is found in duckduckgo image search results: View file at https://duckduckgo.com/?t=ffab&q=arvak&iax=images&ia=images&iai=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2F28%2F86%2F42%2F288642dec69cb52611e17a2afadc940e.jpg

**Comment by anudeepND** [comment]
@mkb2091 Thanks for the info. It will be removed in the next update
