### ISSUE TITLE
www.bing.com - false positive

### ISSUE THREAD

**Issue by CyanoTex** [anudeepND/blacklist#115]
``www.bing.com`` is blocked. False positive.

**Comment by dnmTX** [comment]
No,it's not blocked !

**Comment by kowith337** [comment]
Did you've use Windows Spy Extra or something that block some domains from `Microsoft`?

**Comment by CyanoTex** [comment]
![Screenshot_20200806-152719739 (1).jpg](https://user-images.githubusercontent.com/62466866/89543912-cdf25880-d801-11ea-82a2-e21c95cff67a.jpg)
