### ISSUE TITLE
Suggestion: lptag.liveperson.net

### ISSUE THREAD

**Issue by Ghalid** [anudeepND/blacklist#117]
A lot of subdomains of `liveperson.net` are blocked by this list. I saw a request to `lptag.liveperson.net` (specifically, the resource `https://lptag.liveperson.net/tag/tag.js`, which seems to be a tracking script?), and it seems that this domain is missing from the list.

**Comment by anudeepND** [comment]
@Ghalid Thanks for the info. I will take a look at these domains
