### ISSUE TITLE
Blocking tools.google.com breaks Chrome updates

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/blacklist#12]
Hello and thank you for this great list. I've found that blocking `tools.google.com` in `adservers.txt` breaks google chrome updates. This is unfortunate since I love blocking Google and avoid Chrome whenever possible - but unfortunately it is required for some sites and having an out-of-date version is a big security problem. Anyways, I've whitelisted it on my side, so no real problem, just thought you might want to take this issue into consideration.

![image](https://user-images.githubusercontent.com/598803/43139631-c552c058-8f41-11e8-8514-6d25c5c2ce25.png)

**Comment by anudeepND** [comment]
@lightswitch05 Thanks for the information I will remove it ASAP

**Comment by anudeepND** [comment]
@lightswitch05 Done. Thanks for the input
