### ISSUE TITLE
cnn.com breakage due to data.api.cnn.io

### ISSUE THREAD

**Issue by crssi** [anudeepND/blacklist#121]
Visit `https://edition.cnn.com/middleeast/live-news/lebanon-beirut-explosion-live-updates-dle-intl/index.html` and you will notice a breakage due to `data.api.cnn.io` listing.

Cheers

**Comment by anudeepND** [comment]
Can confirm. Thanks for reporting, it will be removed in the next update.

**Comment by crssi** [comment]
You are a 💎 😄
