### ISSUE TITLE
Blocking clients6.google.com prevents meetings/calls on meet.google.com and duo.google.com

### ISSUE THREAD

**Issue by benzimmer** [anudeepND/blacklist#123]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
clients6.google.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

The domain was added in https://github.com/anudeepND/blacklist/commit/a4d6ee633a9d1cea9e3e58084f69fddf3a6c043d#diff-cc22cd07c68c578554231f7e53fe7de8R43106 and blocks at least Google Meet and Google Duo from being able to join or start a new meeting/call.

To reproduce go to https://meet.google.com and try to start (needs account) or join a meeting. Network inspector in browser devtools will show that the browser was not able to fetch hangouts.clients6.google.com and joining or starting a meeting will fail.

**Comment by anudeepND** [comment]
@benzimmer Thanks for reporting. It was added by mistake, i will remove it ASAP
