### ISSUE TITLE
Rename repo to block-list?

### ISSUE THREAD

**Issue by OmgImAlexis** [anudeepND/blacklist#124]
In keeping up with https://github.com/github/renaming it'd be nice to have this repo and https://github.com/anudeepND/whitelist updated to be deny-list and allow-list respectively.

Since GitHub will forward the old names over this shouldn't be much of a chance nor should I cause any issues for users.

**Comment by anudeepND** [comment]
This has been already discussed - https://github.com/anudeepND/blacklist/issues/112
