### ISSUE TITLE
syndication.twitter.com

### ISSUE THREAD

**Issue by crssi** [anudeepND/blacklist#126]
Hi

I can see that `syndication.twitter.com` leads to breakages on pages with twits since it listed in your blacklist.

Just saying, its not even a request, but just out of curiosity... is there a reason to be listed?

Thank you and cheers

**Comment by anudeepND** [comment]
This was added back in 2018. Do you have any links or screenshots about the issue? 

**More info:** 

- Flagged as tracker by https://whotracks.me/trackers/twitter_syndication.html
- The domain is also blocked in [EasyList](https://easylist.to/easylist/easyprivacy.txt)

![chrome_XKBScVEy4h](https://user-images.githubusercontent.com/26179946/94990661-85ee7880-059b-11eb-905d-b9f8dc53258f.png)

**Comment by crssi** [comment]
Sure.. here is one example site `https://www.24ur.com/novice/korona/neuradno-v-petek-novih-227-primerov-okuzbe.html`

Maybe the rule `||syndication.twitter.com^` was sometime in the past in `EasyList`, but it is not the anymore.

Cheers

**Comment by anudeepND** [comment]
Thanks for the link, I can confirm that it is a false positive. It will be removed in the next update.

**Comment by crssi** [comment]
No problem mate.

Wish you all best and thank you for your work
