### ISSUE TITLE
d9hhrg4mnvzow.cloudfront.net

### ISSUE THREAD

**Issue by zappe** [anudeepND/blacklist#128]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
d9hhrg4mnvzow.cloudfront.net
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Needed for minatjanster.se

**Comment by anudeepND** [comment]
Thanks for reporting, can confirm the issue. I will remove the domain in the next update.
