### ISSUE TITLE
More domains that should be blocked: Request

### ISSUE THREAD

**Issue by MrWaste** [anudeepND/blacklist#129]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s): Add more to your lists, here. Check these out.
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [X] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [X] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
log.zoom.us
logfiles-va-3.zoom.us
logfiles-va-4.zoom.us
logfiles-va-5.zoom.us
logfiles-va-6.zoom.us
logfiles-va-za1.zoom.us
logfiles-va-zd1.zoom.us
logfiles-va.zoom.us
logfiles.zoom.us
us04logfiles.zoom.us

Some more to check out.
analytics.chegg.com

Using the Gomlab Music App. Doesn't ping on the website only the APP. Website: https://www.gomlab.com/
log.gomlab.com
gomlab-log-17054681.us-east-1.elb.amazonaws.com

Grammarly
f-log-editor.grammarly.io Link: https://f-log-editor.grammarly.io/logv2


atc-edge.studybreakmedia.com Link: https://atc-edge.studybreakmedia.com/assets/av/contrib.ads.css
Website: https://www.citationmachine.net/apa
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Website for the zoom trackers, check it out.
https://www.reddit.com/r/pihole/comments/fplgd5/zoomus_trackers/

This was all on the website of www.citationmachine.net This could be use full to you :)

https://cdn.optimizely.com/js/17132650691.js
https://data.studybreakmedia.com:8888/
https://atc-edge.studybreakmedia.com/assets/av/confiant-prebid-2.js
https://contributor.google.com/scripts/70c5121b4f338c10/loader.js
https://media.studybreakmedia.com/doubleclick/ads2.js
https://www.googletagservices.com/tag/js/gpt.js
https://www.googletagmanager.com/gtm.js?id=GTM-PR4ZBX&gtm_auth=S4n_BGrW5rrjm6vmQeG8yQ&gtm_preview=env-1&gtm_cookies_win=x
https://fundingchoicesmessages.google.com/f/AGSKWxX0cpj3UKyl7_PcO_FywHimi82YnJeCdmTweA1Off3AHUBIF580JKnQ8Ys6P6KUvwi05_-7NQOqBI8po3r-ukI=
https://www.gstatic.com/0emn/f/p/70c5121b4f338c10.js?usqp=CA4
https://fundingchoicesmessages.google.com/l/AGSKWxWn1Xy8mWn0aJI1s4hhJ4HDree6fRLqc1N76vJ8P2BM8TsnxEDxckdo7Gq89VpBhArbmraIMHPquP0ADK-P?sbf=2
https://js-agent.newrelic.com/nr-spa-1184.min.js
https://chegginc.demdex.net/id?d_visid_ver=4.2.0&d_fieldgroup=MC&d_rtbd=json&d_ver=2&d_verify=1&d_orgid=3FE7CBC1556605A77F000101%40AdobeOrg&d_nsid=0&ts=&cache_buster=350360095
https://atc-edge.studybreakmedia.com/assets/av/contrib.ads.css
https://pubads.g.doubleclick.net/gampad/adx?iu=/4648849/CM_D_PERSISTENT_VID_TRACKING&sz=1x1&c=16ae1e14-1012-4897-bc4d-6b1d59633a26&t=tracking%3Dplayer_load%26tg%3D1-c
https://c.amazon-adsystem.com/aax2/apstag.js
https://assets.adobedtm.com/e157c7ff34e2d6bd3c151937f4c67f693db0150f/satelliteLib-c1031098c10bfbe330181ddd96ac8850d00f040d.js
https://confiant-integrations.global.ssl.fastly.net/dg8FQdBkd_ja2h9RpFznGYxbsw0/gpt_and_prebid/config.js
https://js-sec.indexww.com/um/ixmatch.html
https://imasdk.googleapis.com/js/sdkloader/ima3.js

**Comment by MrWaste** [comment]
If you want more domains I have more, just message me if interested.

**Comment by MrWaste** [comment]
@spirillen

Please add Watson Telemetry
watson.alpha.telemetry.microsoft.com
watson.df.telemetry.microsoft.com
watson.telemetry.microsoft.com.nsatc.net
watson2.alpha.telemetry.microsoft.com
watson7.alpha.telemetry.microsoft.com

DeveloprDan has tons for great different domains that should be blocked.
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by spirillen** [comment]
Hey @MrWaste Could you do me a favor and add it to https://www.mypdns.org/T599 ? I'll be happy to add them tomorrow. (past bedtime now)

**Comment by spirillen** [comment]
Hey @anudeepND you might have a peek into these as well. Currently I haven't checked these up by my self yet, but for the appearance they look like something the telemetry is CNAMEd to.

```
telemetry.microsoft.com.nsatc.net
sqm.telemetry.microsoft.com.nsatc.net
```

I found these in the zone DB...

**Comment by MrWaste** [comment]
*Update*

I have found other domains that should be block for many reasons. I update this list when I see more trackers on my network, I have found more. You should check out the list! If you want to know that those domains are, I can tell you directly. I always remember those trackers or ads..

https://github.com/MrWaste/Ad-BlockList-2019-08-31/blob/master/Pi-Hole%20BackUps/Black%20List/All%20Server%20Black%20List

**Comment by MrWaste** [comment]
Better understanding of gstatic and what's it doing.
https://better.fyi/trackers/gstatic.com/

Found these on websites.

p2-c7yk5kcwmqtue-n3glbwsb7bbwlgti-552937-i2-v6exp3.ds.metric.gstatic.com
p2-c7yk5kcwmqtue-n3glbwsb7bbwlgti-if-v6exp3-v4.metric.gstatic.com
p2-dpsxu5sk7khww-soevxgedvzl2khm5-989853-i1-v6exp3.v4.metric.gstatic.com
p2-dpsxu5sk7khww-soevxgedvzl2khm5-989853-i2-v6exp3.ds.metric.gstatic.com
p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-632987-i1-v6exp3.v4.metric.gstatic.com
p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-632987-i2-v6exp3.ds.metric.gstatic.com
p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-if-v6exp3-v4.metric.gstatic.com
p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-888026-i1-v6exp3.ds.metric.gstatic.com
p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-888026-i2-v6exp3.v4.metric.gstatic.com
p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-if-v6exp3-v4.metric.gstatic.com
p2-ew6kubq3o55rk-hvug6lp32fc3f7e6-656163-i1-v6exp3.v4.metric.gstatic.com
p2-ew6kubq3o55rk-hvug6lp32fc3f7e6-656163-i2-v6exp3.ds.metric.gstatic.com
p2-g3ha6mpc5wweq-cm57ju7dksaketg5-738447-i1-v6exp3.v4.metric.gstatic.com
p2-g3ha6mpc5wweq-cm57ju7dksaketg5-if-v6exp3-v4.metric.gstatic.com
p2-h2p62etpspq34-ddnjfys6ejjgkcse-378803-i1-v6exp3.v4.metric.gstatic.com
p2-h2p62etpspq34-ddnjfys6ejjgkcse-378803-i2-v6exp3.ds.metric.gstatic.com
p2-h2p62etpspq34-ddnjfys6ejjgkcse-if-v6exp3-v4.metric.gstatic.com
p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-286327-i1-v6exp3-ds.metric.ipv6test.net
p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-286327-i2-v6exp3-ds.metric.ipv6test.com
p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-if-v6exp3-v4.metric.gstatic.com
p2-hz6sobtdsvc3e-joit6vf47oyve36l-546518-i2-v6exp3.v4.metric.gstatic.com
p2-hz6sobtdsvc3e-joit6vf47oyve36l-if-v6exp3-v4.metric.gstatic.com
p2-i5562g5kfodlc-mdvvqtpbp3tamfa7-358102-i1-v6exp3.ds.metric.gstatic.com
p2-i5562g5kfodlc-mdvvqtpbp3tamfa7-if-v6exp3-v4.metric.gstatic.com
p2-k5x3fzte35kia-vub5kcizxtu6ce6w-952896-i1-v6exp3.ds.metric.gstatic.com
p2-k5x3fzte35kia-vub5kcizxtu6ce6w-952896-i2-v6exp3.v4.metric.gstatic.com
p2-k5x3fzte35kia-vub5kcizxtu6ce6w-if-v6exp3-v4.metric.gstatic.com
p2-kjkryej3grzuq-lvyeajv7cqx4okj3-573959-i1-v6exp3.v4.metric.gstatic.com
p2-kjkryej3grzuq-lvyeajv7cqx4okj3-if-v6exp3-v4.metric.gstatic.com
p2-mppanvpl4i7x4-3rspfzwixah5rth3-539023-i1-v6exp3.v4.metric.gstatic.com
p2-mppanvpl4i7x4-3rspfzwixah5rth3-539023-i2-v6exp3.ds.metric.gstatic.com
p2-mppanvpl4i7x4-3rspfzwixah5rth3-if-v6exp3-v4.metric.gstatic.com
p2-nkxu37mq2v7oc-2oj5nu3ibzmgfkuv-136269-i1-v6exp3.v4.metric.gstatic.com
p2-nkxu37mq2v7oc-2oj5nu3ibzmgfkuv-if-v6exp3-v4.metric.gstatic.com

**Comment by dnmTX** [comment]
@MrWaste just run Chrome with `--metrics-recording-only` switch. Those domains can not be blocked in hosts file,they're generated on the fly from the browser itself.

**Comment by MrWaste** [comment]
@dnmTX
I'm using brave, uses the same code as Chrome. 
How do I run this inside of chrome?
k, Thanks

**Comment by dnmTX** [comment]
You can do it as long as it Chrome/Chromium. Also basic Googling from your side would've help,don't you think?
![Chromium](https://user-images.githubusercontent.com/34774426/101697316-3f0a7c80-3a3d-11eb-80dc-171489f8498f.png)

**Comment by dnmTX** [comment]
@MrWaste  make sure to leave **space** between the end of "Target:" line and the command line switch:
.......................Brave.exe" --command-switch

**Comment by MrWaste** [comment]
Thank You so much

**Comment by spirillen** [comment]
Have not checked if these already is in the list, but found them in my old archives (RPZ) as I was following up on [gstatic.com](https://www.mypdns.org/T67)

```txt
metric.gstatic.com
anycast1.metric.gstatic.com
stbcast2.metric.gstatic.com
unicast2.metric.gstatic.com
anycast2.metric.gstatic.com
stbcast3.metric.gstatic.com
stbcast4.metric.gstatic.com
v4.metric.gstatic.com
v6exp3-v4.metric.gstatic.com
p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i1-v6exp3-v4.metric.gstatic.com
p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i1-v6exp3-v4.metric.gstatic.com
p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-s1-v6exp3-v4.metric.gstatic.com
p2-n3zurhre4jjvk-can5rb2f2a4urcxh-if-v6exp3-v4.metric.gstatic.com
p2-f6rp6piuxns4u-uzq4vp76bu3w2tso-if-v6exp3-v4.metric.gstatic.com
p2-aahhyknavsj2m-wtnlrzkba6lht33q-if-v6exp3-v4.metric.gstatic.com
p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-if-v6exp3-v4.metric.gstatic.com
stbcast5.metric.gstatic.com
anycast1-stb.metric.gstatic.com
stbcast2-stb.metric.gstatic.com
unicast2-stb.metric.gstatic.com
anycast2-stb.metric.gstatic.com
stbcast3-stb.metric.gstatic.com
stbcast4-stb.metric.gstatic.com
stbcast5-stb.metric.gstatic.com
stbcast-stb.metric.gstatic.com
unicast-stb.metric.gstatic.com
anycast-stb.metric.gstatic.com
ds.metric.gstatic.com
v6exp3-ds.metric.gstatic.com
p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i2-v6exp3-ds.metric.gstatic.com
p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i2-v6exp3-ds.metric.gstatic.com
stbcast.metric.gstatic.com
unicast.metric.gstatic.com
anycast.metric.gstatic.com
maps.gstatic.com
```

The following have been found active by [pyfunceble](https://github.com/funilrys/PyFunceble)

```python
# Generated by PyFunceble (v4.0.0b3.dev) / https://git.io/vpZoI
# Date of generation: 2021-01-09T13:42:42.626345

0.0.0.0 maps.gstatic.com
0.0.0.0 p2-aahhyknavsj2m-wtnlrzkba6lht33q-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-c7yk5kcwmqtue-n3glbwsb7bbwlgti-552937-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-c7yk5kcwmqtue-n3glbwsb7bbwlgti-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-dpsxu5sk7khww-soevxgedvzl2khm5-989853-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-dpsxu5sk7khww-soevxgedvzl2khm5-989853-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-632987-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-632987-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-eakjwxbsrw7jg-mmsbvherjrpnqjci-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-888026-i1-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-888026-i2-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-edgdy5fdd23jc-uq3pguzzcdnpo2nh-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-ew6kubq3o55rk-hvug6lp32fc3f7e6-656163-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-ew6kubq3o55rk-hvug6lp32fc3f7e6-656163-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-f6rp6piuxns4u-uzq4vp76bu3w2tso-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-g3ha6mpc5wweq-cm57ju7dksaketg5-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-g3ha6mpc5wweq-cm57ju7dksaketg5-738447-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-h2p62etpspq34-ddnjfys6ejjgkcse-378803-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-h2p62etpspq34-ddnjfys6ejjgkcse-378803-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-h2p62etpspq34-ddnjfys6ejjgkcse-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-286327-i1-v6exp3-ds.metric.ipv6test.net
0.0.0.0 p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-286327-i2-v6exp3-ds.metric.ipv6test.com
0.0.0.0 p2-hc3r6mz7g74o6-hl6hlhzx57y5yumu-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-hz6sobtdsvc3e-joit6vf47oyve36l-546518-i2-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-hz6sobtdsvc3e-joit6vf47oyve36l-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-i5562g5kfodlc-mdvvqtpbp3tamfa7-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-i5562g5kfodlc-mdvvqtpbp3tamfa7-358102-i1-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-k5x3fzte35kia-vub5kcizxtu6ce6w-952896-i1-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-k5x3fzte35kia-vub5kcizxtu6ce6w-952896-i2-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-k5x3fzte35kia-vub5kcizxtu6ce6w-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-kjkryej3grzuq-lvyeajv7cqx4okj3-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-kjkryej3grzuq-lvyeajv7cqx4okj3-573959-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-mppanvpl4i7x4-3rspfzwixah5rth3-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-mppanvpl4i7x4-3rspfzwixah5rth3-539023-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-mppanvpl4i7x4-3rspfzwixah5rth3-539023-i2-v6exp3.ds.metric.gstatic.com
0.0.0.0 p2-n3zurhre4jjvk-can5rb2f2a4urcxh-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p2-nkxu37mq2v7oc-2oj5nu3ibzmgfkuv-136269-i1-v6exp3.v4.metric.gstatic.com
0.0.0.0 p2-nkxu37mq2v7oc-2oj5nu3ibzmgfkuv-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i1-v6exp3-v4.metric.gstatic.com
0.0.0.0 p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-i2-v6exp3-ds.metric.gstatic.com
0.0.0.0 p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-164149-s1-v6exp3-v4.metric.gstatic.com
0.0.0.0 p4-ajvwyt5lpjazy-us7r2dzqcjsqh7pt-if-v6exp3-v4.metric.gstatic.com
0.0.0.0 p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i1-v6exp3-v4.metric.gstatic.com
0.0.0.0 p5-lj5aujgj7jl7w-r2pmxqvndsgx2im2-931517-i2-v6exp3-ds.metric.gstatic.com
0.0.0.0 v6exp3-ds.metric.gstatic.com
0.0.0.0 v6exp3-v4.metric.gstatic.com
```
