### ISSUE TITLE
3gppnetwork comprhensive domains list

### ISSUE THREAD

**Issue by ghost** [anudeepND/blacklist#13]
I've noticed my cellphone performing requests to _epdg.epc.mncXXX.mccXXX.pub.3gppnetwork.org_ which was not present in your list. So I decided to script a DNS lookup on all the possible subdomain combination on 3gppnetwork.org

```
#!/bin/bash
# First Loop between 000 and 999
for a in `seq -s " " -w 000 999`
do
	#Second loop between 000 and 999
	for b in `seq -s " " -w 000 999`
	do
		#Using dig, try to retrieve the IP address (-t A) on the hostnames
		CONTENT=`dig @1.1.1.1 -t A epdg.epc.mnc$a.mcc$b.pub.3gppnetwork.org`
		#If we find "SOA" in the dig response, means that hostname has no associated IP address
		if [[ $CONTENT =~ .*SOA.* ]]
		then
			echo "epdg.epc.mnc"$a".mcc"$b".pub.3gppnetwork.org" >> 3gpp_dead.txt
		else
			echo "epdg.epc.mnc"$a".mcc"$b".pub.3gppnetwork.org" >> 3gpp_alive.txt
		fi
	done
done
```

Hopefully this can be easily adjusted to cover many other ad-network.
Obviously the ad-network is able to enable/disable any subdomain not picked up today. In that case, you can decide to:
1) Blacklist all the possible subdomain, even if they are not alive (bigger file).
2) Run the script periodically and update the list with only the live subdomains (slow but more accurate results).
3) Switch to more sophisticated mechanisms to ban entirely subdomains (e.g.: *.pub.3gppnetwork.org)

Meanwhile the alive list is attachd
[3gpp_alive.txt](https://github.com/anudeepND/blacklist/files/2258912/3gpp_alive.txt)

**Comment by anudeepND** [comment]
@havoc88 Thanks for the information. But do you have any info on what is`3gppnetwork.org`? I don't know whether it's a tracker or not, if you have any info on this I will include all these domains in my host file

**Comment by kevinenglish-keyw** [comment]
3gppnetwork.org is the root domain for most Cell-over-WiFi calling.  Cell phones participating in WiFi calls make ESP protocol connections to hostnames like: 
 edpg.epc.mnc260.mcc310.pub.3gppnetwork.org

Block these hosts and you block WiFi calls.

**Comment by dnmTX** [comment]
@anudeepND  if those domains are really affecting the WiFi calls as @kevinenglish-keyw  stating please remove them from your lists as due to a poor cell signal in my place i heavily rely on WiFi calling.
Thanks bud,hope you're well 👍

**Comment by anudeepND** [comment]
@kevinenglish-keyw Thanks for letting me know, I was unable to verify these domains at that time. @dnmTX I will remove them ASAP
