### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by scafroglia93** [anudeepND/blacklist#130]
This domain was found inside my firewall ->

privatestats.whatsapp.net

Could it be a blocking domain used for metrics ?

**Comment by spirillen** [comment]
The domain name suggest it at least. It could also be something else, are you capable of posting a full interaction log?

**Comment by anudeepND** [comment]
hmmm...I use WhatsApp on almost all of my devices and this domain never appeared in my logs. However, the hostname itself tells that it is some kind of telemetry so I will add it to the list

**Comment by spirillen** [comment]
Hey @anudeepND The reason I wouldn't just add is, potential, this can also be referring to some kind of chat history or however that trackware (fakebook) is operating, and why I would prefer some more details in advance, more than just react bases on a name suggestion/references.

@scafroglia93 have you tried to block it locally ? if so, what happened?

**Comment by anudeepND** [comment]
I agree, it needs more testing. Also WhatsApp maybe A/B testing something so this domain is not in my logs. 

I will setup a dummy whatsapp app in one of my older phone and capture the packets, I will update my findings here

**Comment by spirillen** [comment]
As my bell was ringing on this record(as seen before somewhere), I looked it up at <https://hosts.ubuntu101.co.za/app/contents/>, but it isn't there...

**Comment by spirillen** [comment]
Hey @anudeepND did you ever find anything on this issue? Did you get the fake-app up and running and testing??
