### ISSUE TITLE
add embrace.io, a tracker, to the blacklist

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#131]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
embrace.io
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
`embrace.io` is `sentry.io` (a user session tracker) but for Android, iOS, tvOS apps.

https://blog.embrace.io/private-by-default

> Embrace exists for one purpose — to provide mobile teams the data and enhanced support they need to ship the best apps possible. This data includes only what is necessary to monitor and debug mobile apps. It consists of three main types:
> * Device environment information. Examples include OS, region, app version, CPU, memory, battery, and network connectivity.
> * In-app technical events. Examples include views/activities, network calls, logs, and web views.
> * In-app user actions. Examples include taps, button presses, swipes, and user flows.

There's likely other subdomains, but I haven't yet been able to pinpoint those.

**Comment by MrWaste** [comment]
How did you find this? @ignoramous
Which app if any?

**Comment by ignoramous** [comment]
Stumbled upon it randomly. Haven't seen any app use it so far, but then again I don't use very many apps.

**Comment by dnmTX** [comment]
@ignoramous blocking `embrace.io` will just block their home page and nothing else. You either provide the tracking **sub**-domains or close that issue altogether. There is just no point.

**Comment by anudeepND** [comment]
Sorry for the late reply everyone. @ignoramous this domain will be added in the next update

**Comment by anudeepND** [comment]
@MrWaste  You should try [HTTP Canary](https://play.google.com/store/apps/details?id=com.guoshi.httpcanary&hl=en&gl=US) app, I use it on my old phones to find trackers and bad domains
