### ISSUE TITLE
Breakage on amway.si due to tags.tiqcdn.com

### ISSUE THREAD

**Issue by crssi** [anudeepND/blacklist#134]
Login at `https://www.amway.si/` is broken due to `tiqcdn.com` and `tags.tiqcdn.com`

Cheers

**Comment by spirillen** [comment]
The challenge as I see it is that tiq is to be considered [BadWare](https://en.wikipedia.org/wiki/Malware) by default, do to the way the `utag.js` is operating (obfuscating) third party SpyWare, Adware, Tracking pixels etc.

I can see in the history book that this domain have it's own debates over the time. However, it is listed, then delisted and then listed again, it seems like a never ending repeat of it's self.

You can by visiting ex. mvps find it currently commented out, not removed. Personally I'll [keep](https://www.mypdns.org/T2633) it blacklisted, as I believe it's more important that users are aware of the threats and then have the ability to make there personal choice before eventually [whitelist](https://www.mypdns.org/w/whitelist/) it locally.

This is my 2 cents about why I believe it should stay.

```bash
wget -qO- 'https://winhelp2002.mvps.org/hosts.txt' | grep 'tiqcdn.com'
# 0.0.0.0 tags.tiqcdn.com #[affects Intel.com/Shaw]
```

**Comment by anudeepND** [comment]
Thanks for the detailed info @spirillen , how bad is the issue @crssi can you post the screenshot?

**Comment by crssi** [comment]
Just checked again and it looks like they made a change on their login and there is no breakage at login ATM.

Can we, please, set this issue on hold?
Should I close it and reopen if needed?
