### ISSUE TITLE
cdns.eu1.gigya.com

### ISSUE THREAD

**Issue by Snaxeko** [anudeepND/blacklist#136]
- [X] Whitelist
- [X] Website Broken

<hr>

### Domain(s):

- Domain(s): 

```
cdns.eu1.gigya.com
```

<hr>

### Details:

- Your Issue Detail: 

1. Go to https://www.6play.fr/le-meilleur-patissier-p_1807/episode-10-saison-9-c_12807511 (or any 6play replay video)
2. Doesn't work until you whitelist the domain said above

Normal behavior: ask the user to logging.

_Note: unfortunately you need to install Widevine to test it._ I saw [somewhere](https://forum.tomsguide.fr/threads/probl%C3%A8me-de-connexion-mytf1-pour-le-replay-de-quotidien.908383/) that TF1 (another french TV channel) replay also uses this domain before asking to logging. Anyway I triplechecked, removed any filter and only blacklisting this domain was broking this website, then removing this filter again and it worked as intended.

**Comment by anudeepND** [comment]
@Snaxeko Thanks for reporting
