### ISSUE TITLE
www.simplehuman.com broken due to staticw2.yotpo.com and yotpo.com

### ISSUE THREAD

**Issue by crssi** [anudeepND/blacklist#138]
STR:
1. Visit `https://www.simplehuman.com/products/rectangular-liner-pocket-step-can-58l-dual-compartment?variant=30245372067971`
2. Switch between **size** options of the item

**Expected result** would be the item/page is updated accordingly to selection.
**Actual results** are that the page is not updated accordingly to selection and some info/pic vanishes.

The culprit is `staticw2.yotpo.com` and in case of NextDNS also is the `yotpo.com`

Cheers

**Comment by spirillen** [comment]
This domain is classified for [tracking](https://www.mypdns.org/w/trackware/) <https://www.mypdns.org/T2348>

```
https://p.yotpo.com/i?e=pv&page=%231%20World%20Life%20Size%20Sex%20Doll%20-%20Best%20TPE%20%26%20Silicone%20Real%20Love%20Doll%20Store&se_va=ImneDNERbKZvmqIaDOy0zLY6ffL1q3w06CdmEnqZ&cx=eyJwdl91dWlkIjo2NDQwMDEzM30&dtm=1603457719200&tid=579670&vp=1000x800&ds=988x6934&vid=1&duid=08f35e6772d85a2d&p=web&tv=js-0.13.2&fp=2559460427&aid=onsite_v2&lang=en-US&cs=UTF-8&tz=Etc%2FUTC&res=1000x800&cd=24&cookie=1&url=https%3A%2F%2Fsexyrealsexdolls.com%2F
```

Alternative related to this domain is


id | name
-- | --
3009404 | yotpo.com
3377203 | w2.yotpo.com
3377204 | staticw2.yotpo.com
3377205 | p.yotpo.com

My recommendations is to keep it, then users can whitelist it, if they feels like it

**Comment by anudeepND** [comment]
https://www.simplehuman.com/ is working fine with the domain blocked, closing
