### ISSUE TITLE
Possible false positives for mozilla

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/blacklist#14]
Hello Anudeep,

Thank you for providing this great blocklist. I do have a question about a couple Mozilla domains:

### blocklists.settings.services.mozilla.com

This URL is used by Firefox and Thunderbird to ban extensions that cause a security threat against its users. More information about how the blocklist works can be found [in this FAQ](https://support.mozilla.org/en-US/kb/add-ons-cause-issues-are-on-blocklist). You can also view the [contents of the blocklist](https://blocked.cdn.mozilla.net/). Some of these extensions look pretty nasty, I definitely would not want them installed on my computer. Perhaps you will consider removing this domain from your lists so that users can remain protected against these malware extensions.

### shavar.services.mozilla.com

From [Mozilla's site](https://wiki.mozilla.org/Services/Shavar):

> Originally designed for phishing protection the protocol was co-opted so that the tracking protection project would be able to publish larger data sets without incurring large bandwidth usage for mobile clients.

So this is Firefox's version of Google's 'Safe Browsing' feature. I can see why you would block this, but unfortunately its also the service that provides domains to block for Firefox's built-in tracking protection.

### firefox.settings.services.mozilla.com

I use a Firefox account to sync my setting across devices. My understanding is that everything is fully encrypted using a key derived from the user password and cannot be recovered/decrypted on the server without the users password. I did find that they do store IP addresses for security reasons, but I do not believe it is stored unless you are actively using this service.

-----

I've whitelisted all those domains on my end, so this isn't causing me any trouble, but I thought I might open a ticket so that I could get your viewpoint on them.

**Comment by anudeepND** [comment]
@lightswitch05 Thanks for the information. Really appretiate your help man :)

**Comment by lightswitch05** [comment]
@anudeepND have you ever tried to get this list included in Steven Black's project?

**Comment by anudeepND** [comment]
@lightswitch05 Actually no, but I would love to do that...

**Comment by lightswitch05** [comment]
@anudeepND submit a pull request and see what he says. Here is my old pull request if you want an example of what to include: https://github.com/StevenBlack/hosts/pull/633

**Comment by anudeepND** [comment]
@lightswitch05 thanks for the reference PR, one quick question, how do you deal with the duplicates? Currently what I that is do is that I keep on adding the domains and once (or twice) a month I remove the duplicates.

**Comment by lightswitch05** [comment]
I don't currently do anything about duplicates. I'll search his list before adding something to mine, but if duplicates get added, I've never  removed any entries
