### ISSUE TITLE
Add PostHog, an analytics alternative to Heap, Amplitude, MixPanel

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#143]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
posthog.com
posthog-prod-elb-1956116806.us-west-2.elb.amazonaws.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

PostHog is a new-ish analytics product for websites, mostly. I got the domain above as it was CNAME'd from `phog.ycombinator.com`. Looks like [duckduckgo-tracker](https://hosts.oisd.nl/duckduckgotrackers.php) has PostHog in its blocklist already.

**Comment by spirillen** [comment]
Thanks for your report @ignoramous

**Comment by anudeepND** [comment]
Thank for the info, I will add it in the next update

**Comment by anudeepND** [comment]
Since posthog can be self hosted (just like Matomo analytics), blocking posthog.com does not make any sense

**Comment by spirillen** [comment]
> Since posthog can be self hosted (just like Matomo analytics), blocking posthog.com does not make any sense

Well that is to debate, but I blacklist it to avoid other from bad ideas....

**Comment by ignoramous** [comment]
> Since posthog can be self hosted (just like Matomo analytics), blocking posthog.com does not make any sense

[Google Tag Manager](https://chromium.woolyss.com/f/HTML-Google-Tag-Manager-the-new-anti-adblock-weapon.html) can also be self hosted...

**Comment by anudeepND** [comment]
No, you can't selfhost GTM. However you can deliver the GTM code from a different domain or a subdomain which is different from self hosting
