### ISSUE TITLE
Should graph.instagram.com be blocked?

### ISSUE THREAD

**Issue by crssi** [anudeepND/blacklist#145]
See:
`https://www.reddit.com/r/pihole/comments/bmwywq/is_graphinstagramcom_linked_to_ios_facebook/`
and
`https://github.com/StevenBlack/hosts/issues/1206`

Cheers and wish you best in 2021 🥳

**Comment by spirillen** [comment]
absolutely, it's tracking, just try do a search here on  GH for that domain or [here](https://www.mypdns.org/T1224) However, some will say not, as it will break some useless shit

**Comment by crssi** [comment]
Thank you @spirillen 

But... It is the same as it is with `graph.facebook.com`.
Or both should be listed and left for end user to allow when needed so, or both should be unlisted and left for end user to deny when needed.

**Comment by spirillen** [comment]
> Thank you @spirillen
> 
> But... It is the same as it is with `graph.facebook.com`.
> Or both should be listed and left for end user to allow when needed so, or both should be unlisted and left for end user to deny when needed.

Couldn't agree more :smiley:

**Comment by anudeepND** [comment]
Sorry for the late reply, I have been receiving reports about `graph.facebook.com` and `graph.instagram.com`.  I can move `graph.instagram.com` to facebook.txt
