### ISSUE TITLE
apple.tt.omtrdc.net is blocking payments (through iDeal) at apple.com

### ISSUE THREAD

**Issue by notDavid** [anudeepND/blacklist#146]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
apple.tt.omtrdc.net
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
iDeal payments at apple.com are being blocked which results in the purchase process freezing. My dnscrypt log says:

*.omtrdc.net (alias for [securemvt.apple.com])

**Comment by anudeepND** [comment]
@notDavid Thanks for the info, I will remove it in the next update
