### ISSUE TITLE
MTV Suomi crashes on startup, Samsung TV

### ISSUE THREAD

**Issue by cuetus** [anudeepND/blacklist#150]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
tvx.adgrx.com, fi-mtv3.videoplaza.tv
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Most definitely those domains are ad related, should these be listed on 'common issues' or is that list for items with larger audiences only? With these domains blacklisted 'mtv suomi' app on Samsung TV crashes on startup. With these whitelisted everything seems to work, but some ads are playing during watching and some ads just show black screen for a second and player skips to next one. MTV is Finnish TV station, https://www.mtv.fi.

**Comment by anudeepND** [comment]
Sorry for the reply, as you said, these are ad server related.  I think it is better to mention in the 'common issues' section. Thanks for the info :)
