### ISSUE TITLE
Add salpato.numo.in to denylist

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#153]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
salpato.numo.in
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Web analytics, tracker, spyware.

Used by https://archive.is/NfjTG

**Comment by anudeepND** [comment]
I don't see that domain in the link you provided, can you provide more info about `salpato.numo.in`?

**Comment by ignoramous** [comment]
IIM-B now doesn't seem to use it, but [salpato.numo.in](https://archive.md/xgedN) webpage makes it clear that they're an APM / tracker.
