### ISSUE TITLE
Zoom stopped working

### ISSUE THREAD

**Issue by 251** [anudeepND/blacklist#156]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
logfiles.zoom.us
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Zoom stopped working: shows "Connecting..." but never joins a meeting. After whitelisting the domain above it worked again. I'm not sure about the other `logfiles-*zoom.us` domains but for me it seems to work now.

**Comment by 251** [comment]
Note: stopped working again and I had to whitelist `*.zoom.us`.

**Comment by anudeepND** [comment]
This is interesting, I use Zoom everyday and I didn't had any problems with my Zoom meetings. Can you provide more info about your setup?

**Comment by 251** [comment]
I use the Zoom 5.6.7 Linux client and your blacklist on a Pi-Hole v5.3.1.

**Comment by anudeepND** [comment]
Thanks for getting back with the info, I will try to reproduce the issue
