### ISSUE TITLE
Add ConvertFlow domains to denylist

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#158]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
convertflow.com
customers.convertflow.com
www.convertflow.com

convertflow.co
js.convertflow.co
img.convertflow.co
uploads.convertflow.co
app.convertflow.co
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
`ConvertFlow` is a customer marketing platform. I stumbled upon it on `blog.close.com`.

**Comment by spirillen** [comment]
Thanks for sharing these founds @ignoramous :100: :trophy:

**Comment by anudeepND** [comment]
This is similar to #161, Convertflow has lot of elements like forms and sticky elements on the page, blocking it will break a lot of sites
