### ISSUE TITLE
Add Omappapi.com to the denylist

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#161]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
api.omappapi.com
app.omappapi.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Stumbled upon `omappapi.com` on yourstory.com. Looks like some form of marketing training tool.

**Comment by anudeepND** [comment]
Sorry for the late reply, It is from https://optinmonster.com/, by looking at the website, they have marketing tools that enables you to have dynamic content on websites, blocking `omappapi.com` will break many websites.

**Comment by spirillen** [comment]
Easylist is blocking the domain globally.... https://github.com/easylist/easylist/commit/6d91cf977e5#diff-660ac35bad3047b69417687a0169bea3b9f93ff1710509c7c0fa63deea7f109eR1574
