### ISSUE TITLE
Add api.rollbar.com to denylist

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#162]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
rollbar.com
api.rollbar.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
`rollbar.com` cross-platform SDKs are used for error-tracking and other metrics collections. Found this entry in my DNS logs.

**Comment by spirillen** [comment]
Not checked your file, but have these related from own archive: <https://www.mypdns.org/T3824>

```
comapi.rollbar.com
rollbar.comapi.rollbar.com
microsoft.comapi.rollbar.com
telemetry.microsoft.comapi.rollbar.com
mail.rollbar.com
rollbar.com
ping.rollbar.com
changelog.rollbar.com
api.rollbar.com
watson.telemetry.microsoft.comapi.rollbar.com
email.mail.rollbar.com
cemail.rollbar.com
cdn.rollbar.com
docs.rollbar.com
status.rollbar.com
api-alt.rollbar.com
www.rollbar.com
try.rollbar.com
www.try.rollbar.com
```

**Comment by anudeepND** [comment]
Thanks for the info, I will add it in the next update
