### ISSUE TITLE
crashlytics.com

### ISSUE THREAD

**Issue by aravindvnair99** [anudeepND/blacklist#163]
[Firebase Crashlytics](https://firebase.google.com/products/crashlytics) is a lightweight, realtime crash reporter that helps developers track, prioritize, and fix stability issues that erode app quality. Crashlytics saves developers troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

I don't think Crashlytics should be blocked. It's used in various apps and is useful for a lot of developers.

**Comment by kowith337** [comment]
Just for developers, yes, imight helpful...

But not for consumer level, I think...

**Comment by aravindvnair99** [comment]
> Just for developers, yes, it might helpful...
> 
> But not for consumer level, I think...

@kowith337 Ummm I didn't get you... Could you elaborate?

**Comment by kowith337** [comment]
I don't know is crashlytics can let users submit errors back to developers manually or not, but many ppls see some requests to subdomain of `crashlytics`, also some `*-pa.googleapis.com` endpoint that also related to that.

That's why I said it's not good for consumers or normal users.

**Comment by aravindvnair99** [comment]
> I don't know is `crashlytics` can let users submit errors back to developers manually or not, but many ppls see some requests to subdomain of `crashlytics`, also some `*-pa.googleapis.com` endpoint that also related to that.
> 
> That's why I said it's not good for consumers or normal users.

@kowith337 There is an option for manual uploading. It's up to the developer to decide whether to implement or not though. Here's the documentation for it: https://firebase.google.com/docs/crashlytics/customize-crash-reports?#enable-reporting

I don't think `*-pa.googleapis.com` is relevant to this. Those domains are different APIs of Google. Each subdomain having it's own function.

**Comment by anudeepND** [comment]
Sorry for the late reply, crashlytics will not be removed from the list. Please refer https://github.com/StevenBlack/hosts/issues/1566
