### ISSUE TITLE
www.msn.com is blocked

### ISSUE THREAD

**Issue by louisgtwo** [anudeepND/blacklist#166]
https://www.msn.com is blocked because a-msedge.net is on adservers.txt.

**Comment by spirillen** [comment]
First of That domain should not be there, secondly, it is only a issue for you as you are blocking it as wildcard.

```
drill www.msn.com @9.9.9.9

www.msn.com.    12738   IN      CNAME   www-msn-com.a-0003.a-msedge.net.
www-msn-com.a-0003.a-msedge.net.        171     IN      CNAME   a-0003.a-msedge.net.
a-0003.a-msedge.net.    101     IN      A       204.79.197.203
```

As you can see (for this query), then `www.msn.com` is redirected to `a-0003.a-msedge.net` 

So we should probably remove `0.0.0.0 a-msedge.net`

**Comment by anudeepND** [comment]
Sorry for the late reply. Can confirm the issue, I will take a look at it later. Thanks for the info
