### ISSUE TITLE
Add Bitcoin Bootstrap to the list.

### ISSUE THREAD

**Issue by tg12** [anudeepND/blacklist#167]
Add Bitcoin Bootstrap to the list.

seed.bitcoin.sipa.be
dnsseed.bluematt.me
dnsseed.bitcoin.dashjr.org
seed.bitcoinstats.com
seed.bitcoin.jonasschnelli.ch
seed.btc.petertodd.org
seed.bitcoin.sprovoost.nl
dnsseed.emzy.de
seed.bitcoin.wiz.biz

**Comment by anudeepND** [comment]
@tg12 These domains seems to be useful? Any reason for these domains to be blocked? 
https://bitcoin.stackexchange.com/questions/14371/what-is-a-dns-seed-node-vs-a-seed-node

**Comment by tg12** [comment]
It's really down to personal preference. I'd keep them blocked as I don't want Bitcoin mining on my network. Especially the initial bootstrap.
