### ISSUE TITLE
Revisit gigya.com blocking rules?

### ISSUE THREAD

**Issue by timtucker** [anudeepND/blacklist#169]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
*.gigya.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Past blocking of some Gigya / SAP Customer Data Cloud domains was based on their tracking functionality

As of January 2021, SAP retired the tracking functionality from their Gigya product (Signals / Counters) along with all their "social engagement" functionality, which mostly just leaves their login & user management functionality.

From quick testing, our site uses their SDK for logins and I'm no longer seeing the calls to the counters domains / endpoints.  The remaining blocking rules for gigya.com could probably be revisited.

See this announcement from SAP:
https://help.sap.com/viewer/8b8d6fffe113457094a17701f63e3d6a/GIGYA/en-US/4172960b70b21014bbc5a10ce4041860.html

**Comment by anudeepND** [comment]
@timtucker Sorry for the late reply. I will take a look at this issue later, thanks for providing the info.
