### ISSUE TITLE
Deny app-signal, an APM for SaaS apps

### ISSUE THREAD

**Issue by ignoramous** [anudeepND/blacklist#170]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
appsignal.com
appsignal-endpoint.net
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
AppSignal's an APM (tracker) for server-side apps and the web.

From their docs: archive.is/wnfvU and archive.is/d2ybp

**Comment by anudeepND** [comment]
AppSignal is widely used by many developers to monitor and collect metrics related to their application. I think it is not possible to block tracking without affecting other services. I will keep this open so others can post their views

**Comment by spirillen** [comment]
I don't see why this shouldn't be blocked along with [sentry.io](https://mypdns.org/search?scope=issues&search=sentry.io)

**Comment by anudeepND** [comment]
Appsignal also offers uptime monitor etc. so blocking Appsignal will cause more issue I guess. Maybe looking into the privacy policy of each company can help
