### ISSUE TITLE
Add messiah.id to denylist

### ISSUE THREAD

**Issue by Hh12uGMLB** [anudeepND/blacklist#172]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
https://messiah.id/api/event
https://messiah.id/
https://messiah.id/js/script.js
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- `https://messiah.id/js/script.js` tracks pageview events and sends it to https://messiah.id/api/event, saving on their server and then sending to Facebook API

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/2729

</details>

**Comment by anudeepND** [comment]
@Hh12uGMLB Sorry for the delay. The list has been updated
