### ISSUE TITLE
New Domain + IP

### ISSUE THREAD

**Issue by Hh12uGMLB** [anudeepND/blacklist#173]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
rescuemetrics.com
15.197.227.255
3.33.254.229
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:

**Comment by spirillen** [comment]
The domain is rather self explaning, but what for the IP's 

PS: You know you can't block ip addresses from a hosts file? but you are welcome to throw them at https://mypdns.org/my-privacy-dns/matrix/ RPZ zones love IP addresses :smirk:

**Comment by anudeepND** [comment]
@Hh12uGMLB Thanks for reporting. I have updated the list
