### ISSUE TITLE
New domain serving ad 

### ISSUE THREAD

**Issue by alanjacobmathew** [anudeepND/blacklist#177]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
https://glimpsemankind.com/
ad example url: https://glimpsemankind.com/e4fwp7vp?key=0f22c1fd609f13cb7947c8cabfe1a90d
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:

**Comment by alanjacobmathew** [comment]
Another URL used to serve ad
### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
http://kneesfrostcompare.com/
ad example url: http://kneesfrostcompare.com/e4fwp7vp?key=0f22c1fd609f13cb7947c8cabfe1a90d

```


<!-- Example; for **Whitelisting/Blacklisting/Log** type at the beginning and ending of the list.

**Comment by anudeepND** [comment]
@alanjacobmathew Thanks for submitting these domains, I will add these to the list in the next update
