### ISSUE TITLE
g.alicdn.com blocked

### ISSUE THREAD

**Issue by Retia-Adolf** [anudeepND/blacklist#18]
This rule `||g.alicdn.com^` that simply blocking makes site `taobao.com` broken. It's unnecessary since similar but more precise rules are exist in `Easylist China` etc..

**Comment by anudeepND** [comment]
@Retia-Adolf thanks for reporting, I will remove it once I reach home.

**Comment by anudeepND** [comment]
@Retia-Adolf Sorry for the delay, it's now removed
