### ISSUE TITLE
Blocking of improving.duckduckgo.com?

### ISSUE THREAD

**Issue by KeithSieman** [anudeepND/blacklist#183]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
improving.duckduckgo.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Not sure why improving.duckduckgo.com is blocked.  Non-tracking form of A/B testing for the search engine.  Please see this link for more information: https://help.duckduckgo.com/duckduckgo-help-pages/privacy/atb/  This is causing random functionality breaks.

**Comment by anudeepND** [comment]
@KeithSieman Thanks for the feedback. Let's wait for the responses from https://github.com/StevenBlack/hosts/issues/1826
