### ISSUE TITLE
How do I install this blacklist?

### ISSUE THREAD

**Issue by dvpetta** [anudeepND/blacklist#185]
Sorry if this is not meant to be here but I'm unsure of how to use this blacklist with my pihole. 

I recently had to reset my pihole and now it doesn't seem to be working and there are no blacklists loaded.

Am I able to load this into my pihole?  I don't see any instructions like what I saw in your whitelist repo.

Thanks,

Daniel

**Comment by anudeepND** [comment]
Hi Daniel, it's pretty simple, first copy this link - `https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt` and follow the screen recorder.

https://user-images.githubusercontent.com/26179946/152397070-cdd1ce4b-ac39-45df-82c6-912e7da82dbf.mp4

**Comment by dvpetta** [comment]
Thank you so much!  I had added the list but didn't know about that update step!
