### ISSUE TITLE
阻止 app.market.xiaomi.com？

### ISSUE THREAD

**Issue by MySoul182** [anudeepND/blacklist#187]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
app.market.xiaomi.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
它阻止了小米手机应用商店的一些页面
![Screenshot_2022-02-16-17-22-40-028_com xiaomi market](https://user-images.githubusercontent.com/95344231/154240476-25008a7b-eae0-40f1-91b3-486f760bdd9b.jpg)
![Screenshot_2022-02-16-17-22-44-078_com xiaomi market](https://user-images.githubusercontent.com/95344231/154240519-2e78e10d-6bea-47c0-a503-aaf80df6a629.jpg)

**Comment by anudeepND** [comment]
@MySoul182 Thanks for reporting, I have removed `app.market.xiaomi.com` along with other xiaomi domains
