### ISSUE TITLE
Unblock unacademy domain

### ISSUE THREAD

**Issue by agneevX** [anudeepND/blacklist#189]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): 

```
data.unacademy.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

This domain is for recording the duration of watched time, and if its blocked, it does not count towards the user's watched time.

I've gone through the POST data and it does not send anything other than what's directly relevant towards counting watch time from the user.

**Comment by anudeepND** [comment]
@agneevX Thanks for your valuable feedback, the domain is now removed from the list
