### ISSUE TITLE
[Info] Reference

### ISSUE THREAD

**Issue by funilrys** [anudeepND/blacklist#19]
Hello @anudeepND  ,

Because I want to be transparent, I just wanted to inform you that we added your hosts file to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server](https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by anudeepND** [comment]
@funilrys This is great! I'm happy that you considered my list. If you find any false positives I will remove it. Thanks again :)

**Comment by dnmTX** [comment]
@anudeepND  [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) is filtering against dead/invalid domains not false positives.You can use it(once it's filtered) to update your database every week or so.This way there will be no "dead weight",it's super handy.

**Comment by funilrys** [comment]
Hi @anudeepND, glad to hear that!

It's already there ==> https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/templates/README_template.md#credits--thanks

No action is needed from your side. Our next compilation (or run if you prefer) is in about 21 hours. So you'll be in the `README.md` in about 21 hours :smile_cat: 

Have a nice day/night!

Cheers,
Nissar
