### ISSUE TITLE
Adblock Syntax

### ISSUE THREAD

**Issue by RicoHeat** [anudeepND/blacklist#191]
@anudeepND 
First I would like to say that I really love using your Anudeep Blacklist for DNS purposes.. My issue is really not an issue.. I just would like to kindly request for a version of your list using Adblock Syntax if possible.. I would greatly appreciate it.. Other than that.. I just would like to say THANKS for your quality work.. Have a great day!! 👍

**Comment by anudeepND** [comment]
@RicoHeat I use this list in Ublock Origin without converting it to adblock syntax, can you try adding the URL to your extension?

**Comment by RicoHeat** [comment]
> @RicoHeat I use this list in Ublock Origin without converting it to adblock syntax, can you try adding the URL to your extension?

@anudeepND  OK.. No problem.
