### ISSUE TITLE
Remove Gravity.com From Blacklist

### ISSUE THREAD

**Issue by carlhancock** [anudeepND/blacklist#192]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Please remove the Gravity.com domain name from the adservers.txt black list.  We recently acquired this domain name and while many years ago it was used for advertising related technology we are not in the business of advertising.  Glad to provide more details.  But please remove the gravity.com domain from the blacklist.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [X] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
gravity.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

The Gravity.com domain name is no longer owned by an ad tech company.  Please remove it from the blacklist as it is no longer being used for advertising tracking purposes.

**Comment by anudeepND** [comment]
@carlhancock Thanks for reporting. The list does not have `gravity.com` but there was another domain `secure-api.gravity.com` which is now removed.
