### ISSUE TITLE
Facebook unable to properly load with blacklist

### ISSUE THREAD

**Issue by BigslimVdub** [anudeepND/blacklist#193]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
Facebook.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Using blocklist [https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt] Facebook is unable to load. Adding whitelists of graph.Facebook.com, b-graph.Facebook.com, and star-mini.c10r.Facebook.com helps but still has broken loading of the app. Disabling this Adblock list allows full function of Facebook.

**Comment by anudeepND** [comment]
Hello @BigslimVdub, facebook list is not for everybody. If you or someone else at your home uses Facebook or Instagram, don't use facebook list. Use only https://hosts.anudeep.me/mirror/adservers.txt

**Comment by BigslimVdub** [comment]
> 

Ok so the list is for totally disabling Facebook, not to just block ads or tracking like typical block lists.

**Comment by anudeepND** [comment]
> > 
> 
> Ok so the list is for totally disabling Facebook, not to just block ads or tracking like typical block lists. 

Yes, ads on Facebook and Instagram cannot be blocked because legit contents like posts, pictures and videos and ads will be delivered from the same domain
