### ISSUE TITLE
Add adv.lihkg.com

### ISSUE THREAD

**Issue by Marcio2536** [anudeepND/blacklist#194]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
adv.lihkg.com
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
The domain has been used by LIHKG forum for ad-serving purposes and it hasn't been included by major blocklist.

Ads are shown when visiting the site.

**Comment by spirillen** [comment]
> Ads are shown when visiting the site.

Sorry, but I don't see which site you referrers to here, could you give a example, and post it to https://mypdns.org/my-privacy-dns/matrix then I take a second look at it for you
