### ISSUE TITLE
Xiaomi phone activation

### ISSUE THREAD

**Issue by rube200** [anudeepND/blacklist#204]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
find.api.micloud.xiaomi.net
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- So after factory reseting my xiaomi, i connected it to wifi and change my dns immediately to my pihole, then i got back to activate menu to verify my account in phone and tried to login, but it failed and said something not connected to internet, so i decided to check my pihole log and found out that domain is needed to active the phone

**Comment by anudeepND** [comment]
Fixed in the latest update
