### ISSUE TITLE
Paramount+ on SkyQ Receiver: tags.tiqcdn.com

### ISSUE THREAD

**Issue by the0bone** [anudeepND/blacklist#207]
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):
- tags.tiqcdn.com

```

```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

Hi,
due to the block of tags.tiqcdn.com Paramount+ is not working on SkyQ Receiver in Germany.

**Comment by spirillen** [comment]
Info sharing from the library https://mypdns.org/my-privacy-dns/matrix/-/issues/966966#comments

> ... Tealium is only a "Tag Manager", which means while `utag.js` facilitates the loading of other tags / advertisements / tracking scripts, the files themselves loaded from this domain are not strictly tracking the users. ...

MEaning, I believe this should be on the [individual users whitelist](https://mypdns.org/my-privacy-dns/matrix#faq)

**Comment by anudeepND** [comment]
@the0bone Unfortunately I cannot remove it from the list as @spirillen said, it is used to server tracking scripts. However I have mentioned it in the readme. 
More info: https://better.fyi/trackers/tiqcdn.com/
