### ISSUE TITLE
[false-positive] s.aolcdn.com

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#21]
@anudeepND  this domain delivers images and blocking it just cripples some web pages.As seen here:
https://www.autoblog.com/2018/10/18/2018-audi-r8-v10-plus-competition-package/

![capture](https://user-images.githubusercontent.com/34774426/47195618-4680e000-d322-11e8-80c0-3919c0727d54.PNG)

**Comment by anudeepND** [comment]
@dnmTX Sorry for the late response. It's been removed.

**Comment by anudeepND** [comment]
@dnmTX I agree. Good find though +1
