### ISSUE TITLE
js.braintreegateway.com is a payment processing host

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/blacklist#25]
Hello,

`js.braintreegateway.com` is used for payment processing. BrainTree is a PayPal owned company that provides credit-card processing forms for any commercial business. More can be read about their JavaScript SDK here: https://developers.braintreepayments.com/start/hello-client/javascript/v3.

By blocking this script, any website that uses BrainTree's SDK for credit card processing will fail, breaking online shopping and checkouts. I had to whitelist it this morning while doing some christmas shopping :)

**Comment by anudeepND** [comment]
@lightswitch05  Thanks for reporting the domain, it's now removed https://github.com/anudeepND/blacklist/commit/463f8dd38546f11487b099c12e86575b41751734
Happy holidays :)
