### ISSUE TITLE
[false-positive] dt.azadicdn.com

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#26]
Here is a link to show the problem and as you can see the whole web page's icons,css etc. coming from that domain and therefore the page is all broken up:
https://dottech.org/167885/how-to-add-more-options-to-right-click-menu-in-chrome-tip/

**Comment by anudeepND** [comment]
Can confirm. I removed `dt.azadicdn.com` https://github.com/anudeepND/blacklist/commit/9856c68d969e7aea786c2e52f0644e7a59e40c4c
Thanks for reporting @dnmTX

**Comment by dnmTX** [comment]
Anytime 👍
