### ISSUE TITLE
c.tadst.com blocked

### ISSUE THREAD

**Issue by abrasive-blueberry** [anudeepND/blacklist#28]
Hi Anudeep,

Please can you remove the domain c.tadst.com from your blocklist, as it is preventing some legitimate content on timeanddate.com from working (logos and maps not loading).

Best regards

**Comment by anudeepND** [comment]
@abrasive-blueberry Thanks for reporting, it is now removed https://github.com/anudeepND/blacklist/commit/34be82892aa92c16fa3bef19cd3690aefe46bcd7
