### ISSUE TITLE
duplicate entries in adservers.txt

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#31]
@anudeepND  found that you have some duplicates.Listing them here so you can remove them:
`b.scorecardresearch.com`
`cdn.teads.tv`
`i.skimresources.com`
`ml.pubnative.net`
`p.skimresources.com`  **-this one has 3 entries**
`trk.vidible.tv`
`t.skimresources.com`
`p.adsymptotic.com`
`nqs-lw3.youboranqs01.com`
`nqs-nl-c6-c2.youboranqs01.com`
`nqs-nl1-c2.youboranqs01.com`
`nqs-nl2.youboranqs01.com`

Close when done.Thanks.

**Comment by anudeepND** [comment]
@dnmTX Thanks, I will remove them ASAP

**Comment by dnmTX** [comment]
On another note:
![capture](https://user-images.githubusercontent.com/34774426/51450441-6693b700-1cf6-11e9-9dfc-2d25631479f3.PNG)

**Comment by dnmTX** [comment]
Hmm...well,you remember i mentioned that i'm getting your list from the [clean.list](https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server/blob/master/clean.list) aaand for some reason it's not there which is kind of a concern.Now i wonder what else is not there.
I'll open a issue there and hopefully @funilrys will be able to figure it out.
Sorry about bothering you here,should've check with your lists here first.

**Comment by dnmTX** [comment]
@anudeepND  just a question,but i was wondering did you ever consider removing the duplicates that are present in StevenBlack's lists.From my point of view,at least on my end your lists here is used as a addition to Steven's,but i'm not sure about anyone else.

**Comment by anudeepND** [comment]
@dnmTX Actually I started adding domains that were missing in Steven's list and then I started every bad domain and I think there are like ~50% unique domain compared to Steven's list.

**Comment by dnmTX** [comment]
They're actually close to 98% unique. Last time i checked,you had around 1000-1500 duplicates out of 30,000+. I was just curious what you think,that's all.

**Comment by anudeepND** [comment]
Oops...my bad

**Comment by anudeepND** [comment]
Duplicates were removed here https://github.com/anudeepND/blacklist/commit/759657328596d733af51847afd1999487a0d07e7 I did not double checked it though..

**Comment by dnmTX** [comment]
One left(missed): `p.skimresources.com` and that's it. Good job 👍 

P.S. Once removed you can finally close this 😉
