### ISSUE TITLE
Parse Error on my app

### ISSUE THREAD

**Issue by Laicure** [anudeepND/blacklist#36]
Hello,

I just want to report this two:

![1](https://user-images.githubusercontent.com/8619566/53302607-e2a39080-389a-11e9-9099-62e614857828.PNG)
![2](https://user-images.githubusercontent.com/8619566/53302608-e2a39080-389a-11e9-92a9-a4b866c61bf0.PNG)

Two domains in one line or... are those intentional?

Thanks!

**Comment by anudeepND** [comment]
No they're no intentional, I will remove it ASAP

**Comment by anudeepND** [comment]
Thanks for letting me know @Laicure. I have removed those invalid domains
