### ISSUE TITLE
Remove ptpb.pw

### ISSUE THREAD

**Issue by xPMo** [anudeepND/blacklist#37]
```bash
$ git blame -L '/ptpb\.pw/,+1' adservers.txt
92f62b7d (Debian 2018-12-10 13:53:25 +0000 32115) 0.0.0.0 ptpb.pw
```

> [ptpb is a lightweight pastebin and url shortener](https://github.com/ptpb/pb)

**Comment by anudeepND** [comment]
@xPMo Sorry for the late response, it's removed now. Thanks for reporting
