### ISSUE TITLE
[click.linksynergy.com] not FP but better to remove it

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#39]
@anudeepND  i'll post a link to test it (it's safe) ,and i'm not saying that the domain in question is false positive but put it simply,it's working as the "man in the middle"(most likely collecting data in the process) but blocking it,one would not be able to reach the final destination.Here is the link(not sure how long will be active but if it's not ,let me know and i'll give you another one),click on the big green **SEE DEAL** button:
https://slickdeals.net/f/12903043-dell-xps-9380-i7-4k-touch-16gb-ddr4-ram-512gb-ssd-376-in-points-1505-tax

There are other redirect domains like this one and i'll try to trace them and report them due to braking of functionality(which i truly hate to be honest)

**Comment by anudeepND** [comment]
@dnmTX I removed the domain, it is an affiliate link

**Comment by dnmTX** [comment]
Thank you 👍
