### ISSUE TITLE
Two pushbullet.com sub domains are blacklisted

### ISSUE THREAD

**Issue by MustardCat** [anudeepND/blacklist#4]
A couple of sub domains for PushBullet (software to mirror notifications to computers/other devices) are listed in adservers.txt and are false positives.

- api.pushbullet.com
- widget.pushbullet.com

I'm not sure what the widget sub domain is used for, but the api sub domain is required for the software to work

**Comment by anudeepND** [comment]
@MustardCat Thanks for reporting :)
