### ISSUE TITLE
[question] adobe-d.openx.net

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#40]
@anudeepND looks like that domain is responsible for downloading Adobe Flash Player.Any input on why it's blocked here?
For reference see: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/451

**Comment by kowith337** [comment]
- Seems to be OpenX ads or tracking
- Are you trying to download Flash Player from Adobe site or somewhere else?

**Comment by dnmTX** [comment]
@kowith337 thanks for responding. I'm actually trying to decide is it safe or not so it could be whitelisted in another repo(see above,i linked the issue for reference).
Based on what you posted looks like it's better to stay blocked.Thanks again 👍

**Comment by dnmTX** [comment]
closing...no further info needed at this time.
