### ISSUE TITLE
feedburner.google.com | feedburner.com

### ISSUE THREAD

**Issue by spirillen** [anudeepND/blacklist#41]
Hi @anudeepND i'm follow the good guys on Ultimate.Hosts.Blacklist by @funilrys

There is a question about the domains i title of issue on the at least these two issues

https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/455 and my own https://github.com/spirillen/rpz-block-list/issues/78

Could you do us that favor to enlighten us about why they are listed

**Comment by anudeepND** [comment]
@spirillen FeedBurner has a monetize option which uses Google Adsense, but I don't know whether the tracking or adserving domain is delivered via feedburner.google.com 

![step7](https://user-images.githubusercontent.com/26179946/58743946-a3b44680-8458-11e9-89c3-05c262c829b9.gif)
