### ISSUE TITLE
akadns.net servers / Windows Update

### ISSUE THREAD

**Issue by beerisgood** [anudeepND/blacklist#47]
You block the following Windows Update servers with your adservers.txt:
   fe2.update.microsoft.com.akadns.net
   sls.update.microsoft.com.akadns.net
   statsfe2.update.microsoft.com.akadns.net

All are legit:

> Microsoft uses global load balancers that can appear in network trace-routes. For example, an endpoint for *.akadns.net might be used to load balance requests to an Azure datacenter, which can change over time.
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions

**Comment by dnmTX** [comment]
I was also wondering about that(see #30).I guess this confirms it.
@beerisgood, @anudeepND  has been away for some time now so it might take a while until those gets removed. Just FYI.

**Comment by beerisgood** [comment]
Looks like the dev is inactive.
After 14 days without any response in other issue https://github.com/anudeepND/blacklist/issues/46 i remove this list from my PiHole until (if ever) fixed.

**Comment by anudeepND** [comment]
@beerisgood @dnmTX Sorry, I was away from Github because of health issues. I will continue to maintain this list.
