### ISSUE TITLE
   vanguard.demdex.net

### ISSUE THREAD

**Issue by chado99** [anudeepND/blacklist#48]
Match found in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:
   vanguard.demdex.net

Hi, Vanguard isn't an ad server. This domain is for the adobe analytics used for personalize services and a few other items on their site. I recommend an unblock as it is not an ad server. Thanks.

**Comment by kowith337** [comment]
`Analytics` should be also treated as Ads and tracking, I guess, must be same as `Google analytics`, isn't it?

**Comment by chado99** [comment]
fair enough. I am more nuanced. distinguish analytics for private company use (e.g, an organization who has adopted adobe platform for their own customer experience, like vanguard). But your point is fair and valid. I will whitelist on my own end for this purpose. feel free to close this.

**Comment by dnmTX** [comment]
@chado99  if you don't mind close this as the repo owner is away at this moment.Thank you 👍

**Comment by chado99** [comment]
c;losed as the point was brought up that this is technically a tracker...just not an ad server.
