### ISSUE TITLE
Domains Breaking AndroidTV Apps

### ISSUE THREAD

**Issue by MattAKAFred** [anudeepND/blacklist#49]
I've had to whitelist a few domains to enable some of my Android TV (SHIELD TV) apps. Specifically:

CBS:
`cbsinteractive.hb.omtrdc.net`
`pubads.g.doubleclick.net`

NBC:
`nbcume.sc.omtrdc.net`

Not confident of your policy on what constitutes a "false positive", but these are necessary for the apps in question to function (though they likely also do assist in serving ads).

**Comment by anudeepND** [comment]
@MattAKAFred You may need to whitelist these domains because doubleclick.net is an adserving domain and omtrdc.net is used for tracking. These domains will not be removed as it affects majority of users.
