### ISSUE TITLE
Inactive domains

### ISSUE THREAD

**Issue by anudeepND** [anudeepND/blacklist#50]
I was looking at the https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server/tree/master/output/domains, there are 13k inactive domains. Most of them seems to taken down or no longer valid. What are your suggestions @dnmTX and @lightswitch05 ? Do I need to remove them?

**Comment by lightswitch05** [comment]
When lists like these are used with something like the pihole - there is very little performance impact to the run-time with long lists. However, there are definite performance issues with using a long list with windows hosts. So I guess its depends on how you expect this list to be used.

Personally, I don't care to remove these inactive domains and people who wish to have an optimized list are welcome to use the one generated by the ultimate-hosts-blacklist project. In the end, Its really up to you and what your own goals for the project are.

**Comment by anudeepND** [comment]
@lightswitch05 Better leave them as it is, we can't be 100% sure that these domains are inactive

**Comment by dnmTX** [comment]
@anudeepND  @lightswitch05  i personally been loading both of your lists from the ultimate-hosts-blacklist project for...probably a year now,it could be even longer and will remain the same way for the feature.For me it's important my lists to be optimized to the max 😉 .But that is just me,and as @lightswitch05  already noted it all comes to personal preference.
