### ISSUE TITLE
fast.wistia.com is a video hosting provider

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/blacklist#52]
Blocking `fast.wistia.com` breaks training videos on codewithmosh.com

My understanding is that `fast.wistia.com` is a hosting provider for videos - kind of like vimeo.com for businesses. While the videos can be advertisements, they can also be legitimate content videos.

**Comment by anudeepND** [comment]
Can confirm, the video on the homepage fails to play. I removed `fast.wistia.com`. Thanks for reporting!
