### ISSUE TITLE
yastatic.net

### ISSUE THREAD

**Issue by xorcan** [anudeepND/blacklist#53]
please remove this line from blacklist:
||yastatic.net^

because its blocking some content:
![resim](https://user-images.githubusercontent.com/25418042/60268047-2c0cf680-98f4-11e9-88bd-b131499b60d0.png)

**Comment by anudeepND** [comment]
Can confirm. Thanks for reporting @xorcan, it's removed in https://github.com/anudeepND/blacklist/commit/09d122e16a7e4aff45e831ec04ffc9094fd1f311
