### ISSUE TITLE
Report Tracker for Windows App

### ISSUE THREAD

**Issue by DRSDavidSoft** [anudeepND/blacklist#60]
These domains belong to [FlashGet](http://flashget.com), which is a Windows download manager app:

### Trackers
```
stat.flashget.com
supertracker.flashget.com
cplog.flashget.com
```

### Ads
```
post.7p.com
```

Could you please consider adding them to your list?

**Comment by anudeepND** [comment]
@DRSDavidSoft Thanks for reporting, I will add them in the next update
