### ISSUE TITLE
[false-positive] sentry.io

### ISSUE THREAD

**Issue by andreas83** [anudeepND/blacklist#61]
i guess sentry.io should not be on that list

**Comment by dnmTX** [comment]
I guess it should

**Comment by kowith337** [comment]
Noted that some app or service use `Sentry` for mail server, e.g. NewPipe app use that for report bug via e-mail and prompted users before reporting back.

However, some web, apps or services can use with abusive way, e.g. logging or capture error and sent them without user confirmation.

But for now, I have no idea is it true?

**Comment by andreas83** [comment]
Please let me explain why i think its a false positive. 
Disclaimer i know at least one guy working there. 

For sure it can be abused for user and behavior tracking but this it not what it is designed for in the very first place. Its basically a tool for developers to track errors. 

From their website: 
Sentry provides open-source and hosted error monitoring that helps all software
teams discover, triage, and prioritize errors in real-time.

**Comment by empurium** [comment]
Agreed, sentry.io is a legitimate company that developers use to track errors in their web apps. That's its only purpose. So if you encounter an error when using a website, the error message is sent to Sentry so that the developers can fix the problem.

We use Sentry daily to find and fix issues for users and/or customers. Just my $0.02.

**Comment by dnmTX** [comment]
Whitelisted on your end and go on with your lives.**SENTRY** will remain blocked here!!!!
That...is...a...PROMISE !!!!

**Comment by kowith337** [comment]
> So if you encounter an error when using a website, the error message is sent to Sentry so that the developers can fix the problem.

To be clear, did that process are done automatically or prompt to user-side before submit error back to `Sentry`?

If not, it maybe in doubt and need to block first.

**Comment by empurium** [comment]
@dnmTX I understand whitelisting is a workaround. I'm only adding some information as to what it is, nothing wrong with that. I don't care if it remains blocked here, though you don't exactly appear to be a contributor to this repository, so I'm not sure why you have such strong feelings.

@kowith337 The user is not typically prompted in most implementations that I've seen, but they don't qualify as an advertiser (it appears in `adservers.txt`). Their goal is to help fix user errors/websites is all I'm saying.

**Comment by dnmTX** [comment]
> though you don't exactly appear to be a contributor to this repository

you can call me **THE GATEKEEPER**

> so I'm not sure why you have such strong feelings

that is truly NON OF YOUR BUSINESS  **Mr. Centry Lover** ,now PISS OFF !!!!

**Comment by empurium** [comment]
Cool attitude for people adding context to a discussion, have fun with that 🤷‍♂ 

Appreciate the repo either way.

**Comment by anudeepND** [comment]
Sorry for the late reply @empurium , this issue has been discussed in https://github.com/lightswitch05/hosts/issues/58, so my response will be same as @lightswitch05

**Comment by empurium** [comment]
Ah, appreciate the insight @anudeepND !
