### ISSUE TITLE
Potential Issue Blocking cdns.gigya.com

### ISSUE THREAD

**Issue by workmanlike** [anudeepND/blacklist#62]
Hello,

Thanks for taking the time to make this list.

Just a quick question: blocking the address: cdns.gigya.com causes the www.nationalexpress.com search functionality to break and after searching online it appears blocking it breaks other websites as well.  Is this a case where people will have to whitelist if they require it otherwise it will be blocked?  It seems to me that this address serves a useful purpose rather than just being an 'adserver'...

**Comment by spirillen** [comment]
Domains Used for ads/tracking/malware are often used for several purpose, exactly to have **_YOU_** whitelisting them as "your" blacklist breaks sites... 
hrm hmm and this is to turn things upside down. It is the evil sites, that code there sites to use evil services, there is broken... and very badly coded.

Summary, whitelisting evil domains is a bad path. The best you can do, is to add `www.nationalexpress.com` to the [bait_site](https://gitlab.com/my-privacy-dns/matrix/matrix/tree/master/source/bait_sites) list if you think this is more rightful and then find a better place for useful information/news

A fast preview of that sites tells me to stay away, personally I wouldn't trust  that site if I landed there from a search page

**Comment by workmanlike** [comment]
Yeah I guess that's a problem if they are using them for multiple things.  Seems strange that they would do that though as DNS blocking isn't exactly mainstream.  

Haha, I wouldn't describe it as a bait site as it's the biggest coach travel company in the UK but I take your point it probably has a lot of trackers on it etc.

**Comment by spirillen** [comment]
> I wouldn't describe it as a bait site as it's the biggest coach travel company in the UK

Google and Facebook are not small either but they are still only bait-sites, seems to offer you something only to harvest your privacy and organs...

A little hint, as bigger something, more evil have been served to get there...

**Comment by anudeepND** [comment]
Gigya is used to build customer behavior data and it should be on the list, @lightswitch05 do you have any info on how it affects www.nationalexpress.com ?

**Comment by lightswitch05** [comment]
I have Gigya blocked in my aggressive list, but not my primary list. I moved it to my aggressive list per https://github.com/StevenBlack/hosts/issues/742#issuecomment-411037366

**Comment by lightswitch05** [comment]
It is interesting that this complaint is for the exact same website. Since its the same website that keeps being complained about, I would be more inclined to add it back to my base list and just have people who need this specific website to whitelist it. When a block seems to only affect a single website like this, the issue tends to be more with the website not doing proper error handling then the blocked service actually being required. Its hard to say which it is in this case without more research.

**Comment by lightswitch05** [comment]
I like @spirillen suggestion that this is a bait site and is designed to fail on purpose

**Comment by spirillen** [comment]
@lightswitch05 and @anudeepND if you should add it to your list or not would depend on the concept of your project.

e.g. My concept is clear: **_Privacy_** and if blocking any tracking/spying is breaking any bad websites, it's a success that hopefully would bring people into better sites. And as long there can't be provided a seriously good argumentation that a domain no longer nor ever will be used for privacy invasive thing... they stays.

@StevenBlack's concept is more we block if it doesn't break, which is the opposed of my personal choices

But according to this line in your README
`A list of adserving and tracking sites maintained by me` I would move all gigya.* to the default list...

My 2 cents

**Comment by spirillen** [comment]
> > @StevenBlack's concept is more we block if it doesn't break
> 
> um, wut?

Hi Steven thx for you reply, It just happens that i been noticing lately that you disable sources if they brake a site.....  I would of curse drag up a few examples here, but as always when you need something you can't find them, but CoinBlocker is one from the top of my head....

**Comment by StevenBlack** [comment]
@spirillen CoinBlockerList had a MAJOR bug that added 3,000 domains that included all digital currency exchanges, AND digital currency quote sites.

So ya I removed that, for a few days, because it was bogus.  It was a serious, third-party bug.

**Comment by spirillen** [comment]
@StevenBlack see edit above :point_up:

**Comment by anudeepND** [comment]
This site will remain blocked, https://better.fyi/trackers/gigya.com/ because of the data it collects and how they process it, their privacy policy looks sketchy to me
