### ISSUE TITLE
Ubiquiti calling home

### ISSUE THREAD

**Issue by Geraner** [anudeepND/blacklist#63]
Just saw those news:
https://www.theregister.co.uk/2019/11/07/ubiquiti_networks_phone_home/
Additional to this, Ubiquiti's own statement:
https://community.ui.com/questions/Update-UniFi-Phone-Home-Performance-Data-Collection/f84a71c9-0b81-4d69-a3b3-45640aba1c8b
Ending with the comment:
_"If you do not wish to participate/provide this data, we will add an opt-out button in upcoming versions that will make it easy to opt-out of providing this data. In the meantime, you can block traffic from UniFi devices to trace.svc.ui.com."_

Maybe this domain is something for you to add to your list. :-)

**Comment by spirillen** [comment]
Hey @Geraner Thanks for the [note](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/520) I have at least added it to my sources :smiley:

**Comment by anudeepND** [comment]
@Geraner This is great! Thanks for notifying me
