### ISSUE TITLE
False positive on the Facebook list instagram.c10r.facebook.com

### ISSUE THREAD

**Issue by TorchedPoseidon** [anudeepND/blacklist#65]
Blocking `instagram.c10r.facebook.com` breaks instagram, in particular viewing one's (own) profile and posts. Whitelisting it makes it work again. 

Edit: To clarify this is on the iOS app

**Comment by LookingSharp** [comment]
FYI - I don't seem to be hitting this.  Not sure if the repro steps aren't clear.

**Comment by TorchedPoseidon** [comment]
@LookingSharp there's not much to describe to repro, but for sake of good form: 

Step 1: Add the Facebook list to your favourite DNS based add blocker, in my case the PiHole
Step 2: Open the Instagram app on iOS
Step 3: Tap on the profile button, last option on the right of the buttons on the tab at the bottom
Step 4: Pull down to refresh for good measure since the app will initially show cached posts or tap on the 'tagged' tab in the upper half of the screen or simply open a profile page of a random person's profile preferably one that couldn't have been cached before.

Expected result: For the profile/tagged posts to load

Actual result: Differs, sometimes it's an endless load until time out, sometimes it's a vague error and sometimes a clear error indicating that there's no connection; either way the actual result is no connection or rather a gimped version of Instagram that doesn't work past the home feed and with the only entry that indicates a block in the PiHole within a reasonable timeframe being instagram.c10r.facebook.com. Whitelisting said URL makes the Instagram app work again.

**Comment by anudeepND** [comment]
@TorchedPoseidon Can confirm. Thanks for reporting
