### ISSUE TITLE
False positive(?) www.opinionstage.com

### ISSUE THREAD

**Issue by TorchedPoseidon** [anudeepND/blacklist#68]
`adservers.txt `includes `www.opinionstage.com` which is used by some newsblogs for a quick and dirty way to poll readers. [Example (Dutch)](https://www.iculture.nl/nieuws/iphone-11-serie-gps-probleem/), they use it regularly.  

I'll leave it up to @anudeepND if that's to be considered a false positive or if it falls within the scope of what the list is trying to block.

**Comment by spirillen** [comment]
For what I can understand from `www.opinionstage.com` site, they are a Spyware/Tracking service!!

> Discover insights while users engage with appealing polls, surveys & quizzes. Get more responses. Analyze results with powerful analytics dashboard.

> Gather High Quality Insights With Personality Quizzes

> Personality quizzes let users discover something new and interesting about themselves, while allowing you to uncover information about them and their preferences. Users participating in a personality quiz, with the promise of discovering something about themselves are more likely to be authentic & truthful in their answers. Otherwise, the quiz outcome won’t have much meaning for them. Read more about Opinion Stage quizzes and their benefits, in the Quiz Maker page.

**Comment by TorchedPoseidon** [comment]
@spirillen Perhaps I'm misreading, but where in that excerpt does it state they are utilising spyware or tracking for that matter?  

All I'm reading is that they pass on the volunteered answers that are filled in in Buzzfeed-esque quizzes to the person that made the quiz and put it up on their webpage. Perhaps for a quiz that might not be immediately obvious to the person filling in the quiz, depending on the documentation on the page where it is hosted but if we're talking about a poll (or even survey) like the one in the example I've listed then such a thing is expected, is it not?  

Either way, at best it's a grey area and it's up to the list curator to determine if it is considered an ad or tracker domain. I brought it up because in it's current state the blacklist prevents me from participating in volunteering information that helps a news outlet asses how prevalent a certain bug or issue is. 

Thus far, I have no reason to believe that the URL in question is involved in serving me an ad or in gathering information that is not volunteered despite it's potential to be used in more pop-media manners.

**Comment by spirillen** [comment]
Hi @TorchedPoseidon thanks for the reply. 

To understand the language of this kind of hrm hrm dudes, we need a little dictionary of translations from there deeply manipulative language to lure people into, wow this is cool. Here is a little simplified one:

> Discover insights
They are tracking all your moves, for designing a personally identifying identity of _YOU_

> Gather High Quality Insights 

Same as above

>> With Personality Quizzes

The quiz is  the tool to identifying you by have do you type, moving your mouse etc. The make a psychological profile of you

> uncover information about them...

Read the 3 points above for how..

>> and their preferences

example your sexual preferences :dancer: 

Do it comes to senses now :question: 

So weather this is a grey area or not... I leave @TorchedPoseidon to answer that  :smiley:

**Comment by TorchedPoseidon** [comment]
I’m sorry @spirillen but this is getting a bit too much levels of tinfoil hat. On that note I’m unsubbing from this issue. It’s reported and discussed, there’s not much to add. The curator @anudeepND will have to make their own determination based on the information at hand. My job here is done.

**Comment by spirillen** [comment]
@TorchedPoseidon try to read this as an example https://seeromega.com/get-user-insight-run-targeted-campaigns-using-personality-quizzes/

https://www.tryinteract.com/blog/gain-customer-insights-using-personality-quizzes/

https://voymedia.com/engage-inspire-and-convert-with-personality-quizzes/

https://www.opinionstage.com/tutorials/how-to-make-a-personality-quiz

Then you can do what you wont with that hat of yours :smiley:

**Comment by TorchedPoseidon** [comment]
@spirillen None of those examples indicate how these quizzes are used to track people without their knowledge or consent nor how they serve unsolicited ads. Moreover none speak about polls. Lastly none indicate which domain is being used to do the stuff you’re alleging. Currently the domain it pertains to leads to a corporate webpage and, if the URL is more than just the mentioned domain, to polls (and apparently quizzes) that are hosted there with no indicators that it does anything else than display said polls and quizzes. Assuming there is no interaction from the user, until shown otherwise I’ve got no reason to believe tracking happens nor that ads are served, despite whichever profile one might concoct after one has volunteered information.

**Comment by anudeepND** [comment]
@TorchedPoseidon Sorry for the late reply. I looked at the privacy policy of [OpinionStage](https://www.opinionstage.com/privacy). Here's a quote from that page:

`
 In some cases, persons may be asked to provide certain personal data through the polls, surveys, quizzes, slideshows, lists, stories and forms created through the Website (the “Content Data”). Please note that we do not make decisions about what personal data is requested as the Content Data or for what purposes such Content Data is used. The user that uses the Services and requests the Content Data is the person who is responsible for handling the Content Data. We merely store and process such personal data on our servers for the purpose of provision of the Services.
`

It is left to user whether he will provide the info or not and I think opinion  stage doesn't automatically collect the personal data. So I will remove it from the list. Thanks for reporting :)
