### ISSUE TITLE
Ubiquiti/Cisco Support sites

### ISSUE THREAD

**Issue by Flyhalf205** [anudeepND/blacklist#7]
https://community.ubnt.com/ uses this domain for its CSS layout. With it blocked the layout is jacked.

- ubnt.i.lithium.com

Also cisco support forums uses this for its CSS layout which is also on this list.

- kxiwq67737.i.lithium.com

There is probably more support sites but I use these two regular

**Comment by anudeepND** [comment]
@Flyhalf205 Thanks for reporting, I think I have to remove all lithium.com subdomains, I too faced some issues on other sites.
I'm currently out of station, I'll review it in 48hrs

**Comment by anudeepND** [comment]
Removed legit domains https://github.com/anudeepND/blacklist/pull/8
@Flyhalf205  Is this issue resolved for you?

**Comment by Flyhalf205** [comment]
Yes. 

Now having a problem with the Facebook app which I'm currently tracking which host it is.

**Comment by anudeepND** [comment]
It was `graph.facebook.com`
Removed it https://github.com/anudeepND/blacklist/commit/044235b329e44f2560888eb105f86a6ae37d34aa

**Comment by anudeepND** [comment]
Check out https://github.com/anudeepND/whitelist for commonly whitelisted domains
