### ISSUE TITLE
Please validate cs11.wpc.v0cdn.net

### ISSUE THREAD

**Issue by dnmTX** [anudeepND/blacklist#73]
@anudeepND  for more info refer to this [issue](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/108) as i'm not convinced so far to whitelist it there.
Please validate and it's up to you to remove it or not.
Thanks bud 👍

**Comment by anudeepND** [comment]
@dnmTX Any updates on this?

**Comment by dnmTX** [comment]
@anudeepND  welcome back my friend,hope everything is ok and you are well 😉 
I'm really not convinced that the mentioned domain is anywhere close to false positive so no action is needed from you and i'll be closing this issue and the one on our end as well.
And one more time....glad you're back 👍

**Comment by XelNika** [comment]
@anudeepND I just hit this issue like the user in the linked issue. `ctldl.windowsupdate.com` *can* be a CNAME to `cs11.wpc.v0cdn.net`, Microsoft seems to load-balance across several CDNs.

I have no opinion on its presence in the list though. If I understand correctly, Pi-hole will allow the lookup if I whitelist `ctldl.windowsupdate.com` so I prefer that solution.

![Screenshot_20200415_111832](https://user-images.githubusercontent.com/14213514/79321128-2cba5c00-7f0b-11ea-88e4-28dd410e9c37.png)

**Comment by anudeepND** [comment]
@XelNika Hmmm....interesting, I have decided to remove `*.v0cdn.net` domains from the list. Thanks for updating me on this issue :)

**Comment by p1r473** [comment]
Thanks for this!
