### ISSUE TITLE
uhf.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [anudeepND/blacklist#74]
This domain is used for bringing Microsoft websites into compliance with the EU cookie policies.
See https://github.com/Rational-Interaction/microsoft-cookie-compliance.

So no candidate for your adservers.txt

@anudeepND

**Comment by anudeepND** [comment]
@beerisgood Thanks for reporting, will be removed in the next update

**Comment by anudeepND** [comment]
@beerisgood The domain is not blocked in the list. Closing

**Comment by beerisgood** [comment]
Thanks!
