### ISSUE TITLE
Parimatch.ru

### ISSUE THREAD

**Issue by unimarijo** [anudeepND/blacklist#76]
Parimatch.ru is the official bookmaking company, it has nothing to do with ads/telemetry.

`www.parimatch.ru` is blocked for some reason, however, `parimatch.ru` is not.

**Comment by anudeepND** [comment]
@unimarijo Thanks for reporting, it was added by mistake. I will remove it in the next update

**Comment by anudeepND** [comment]
Removed in ce987e1
