### ISSUE TITLE
js.pusher.com is not an ad/tracking service

### ISSUE THREAD

**Issue by c0defre4k** [anudeepND/blacklist#77]
Hello,
is there a specific reason why `js.pusher.com` is blocked?
Pusher is a framework used by modern web applications to provide realtime data through web-sockets. Although it can be used for advertising its not the main purpose if this service. Blocking this domain breaks base functionality of many website that use this technology.

In my opinion this should be removed from the list, to not break anything.

**Comment by llacb47** [comment]
Provide examples of breakage.

**Comment by c0defre4k** [comment]
In my case its a backend application to manage the content of a website, which uses pusher to provide live updates instead of reloading the whole page.
Because the `js.pusher.com` is blocked it actually prevents the application from booting and I'm stuck at looking at a loading animation.

[Pusher's website](https://pusher.com/) describes pretty good what this service is used for - this is not a tool used for advertising or tracking.
In the [developer docs](https://pusher.com/docs/channels/getting_started/javascript) you see that they provide their Client SDK through the `js.pusher.com` domain. `ws.pusherapp.com` is the domain where the websocket connection is established to.

Therefore these domains should be removed from the list:
* `ws.pusherapp.com`
* `js.pusher.com`

**Comment by dnmTX** [comment]
@c0defre4k  the lists owner is away at the moment and i'm not sure when he'll be back to validate your request. Will advise you to whitelist it on your end and keep an eye on the issue here for any changes/updates.

**Comment by c0defre4k** [comment]
@dnmTX thanks for the info! That's what I already did in my setup. I'll have an eye on this ticket until the author has reviewed it. I'm sure it wasn't his intention to block a service like this.

**Comment by anudeepND** [comment]
Sorry for the delay guys, I will remove it in the next update :)

**Comment by anudeepND** [comment]
Removed in ce987e1

**Comment by c0defre4k** [comment]
@anudeepND can you please also remove `ws.pusherapp.com`?

**Comment by anudeepND** [comment]
Oops...it will be removed in the next update :)
