### ISSUE TITLE
accounts.us1.gigya.com socialize.us1.gigya.com

### ISSUE THREAD

**Issue by p1r473** [anudeepND/blacklist#79]
Hi, you are blocking the following domains:

accounts.us1.gigya.com
socialize.us1.gigya.com

These domains break logging into iRobot app on Android, and starting iRoomba vacuum from Google Home

**Comment by anudeepND** [comment]
@p1r473 Thanks for reporting, I will look into it

**Comment by anudeepND** [comment]
If anyone has tested with their iRoomba devices please post in this thread

**Comment by p1r473** [comment]
I have tested this
Was not able to log in without these domains unblocked, and couldn't start the iRoomba vacuum from my Google Home

**Comment by anudeepND** [comment]
@p1r473 It is removed in the latest update. Thanks :)
