### ISSUE TITLE
x.ss2.us

### ISSUE THREAD

**Issue by beerisgood** [anudeepND/blacklist#80]
The domain "x.ss2.us" is used for Third party Certificate download and verification sites.

See https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/What-URLs-protocols-should-be-accessible-for-Desktop-Subscription-to-work.html

**Comment by anudeepND** [comment]
@beerisgood Thanks for reporting, will be fixed in the next update

**Comment by anudeepND** [comment]
Removed in ce987e1
