### ISSUE TITLE
arc.msn.com

### ISSUE THREAD

**Issue by beerisgood** [anudeepND/blacklist#81]
Your https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt block the following false positve:
arc.msn.com

It's used/ needed for Windows Spotlight

**Comment by anudeepND** [comment]
@beerisgood Sorry for the late response, I didn't had access to my computer. I will fix it in the next update. I have a list of several MS domains that breaks some functionality across MS platforms, I will remove them in the next update

**Comment by anudeepND** [comment]
Removed in ce987e1
