### ISSUE TITLE
moneycontrol.com

### ISSUE THREAD

**Issue by ajayramaswamy** [anudeepND/blacklist#82]
Please remove stat.moneycontrol.com stat1.moneycontrol.com stat2.moneycontrol.com stat3.moneycontrol.com stat4.moneycontrol.com  stat5.moneycontrol.com

This breaks the ability to go into any article on their side only the first page renders correctly all atricles and other tools are broken

**Comment by anudeepND** [comment]
@ajayramaswamy Thanks for report. Even though the domain name look like trackers, those are used to deliver style sheets and JS files. Will be removed in the next update
