### ISSUE TITLE
browser.sentry-cdn.com

### ISSUE THREAD

**Issue by beerisgood** [anudeepND/blacklist#85]
Blocking this domain break the following site:
https://app.roll20.net/

Login works, but not site roll game.
After allowing, it works

**Comment by anudeepND** [comment]
@beerisgood Thanks for reporting. The sentry domains will be addressed in the upcoming days

**Comment by anudeepND** [comment]
Initially I didn't wanted to remove sentry, but many of the developers use this to capture errors, so I decided to remove sentry.io and browser.sentry-cdn.com. However domains such as sentry.*.tld will be blocked
