### ISSUE TITLE
unblock -> graph.instagram.com

### ISSUE THREAD

**Issue by scafroglia93** [anudeepND/blacklist#86]
Source ->
https://github.com/StevenBlack/hosts/issues/1206

**Comment by anudeepND** [comment]
@Thanks for notifying about the issue. As per the @llacb47 reply, it's also used for tracking events, also graph.facebook.com is also used for serving ads as well as an endpoints for many APIs. @llacb47 Do you any more info on this domain?

**Comment by scafroglia93** [comment]
Maybe you can reopen an issue inside stevenblack ?

**Comment by anudeepND** [comment]
@scafroglia93 It is also used for recording events for non instagram users also, it is better to leave a note on the readme saying the developers who use Facebook/IG APIs should whitelist the domain. What do you think?

**Comment by scafroglia93** [comment]
That would be nice

**Comment by anudeepND** [comment]
Added to the [wiki](https://github.com/anudeepND/blacklist/wiki/Whitelist-Guide)

**Comment by spirillen** [comment]
Which wiki?? It seems disabled to me and therefore redirects to https://github.com/anudeepND/blacklist

**Comment by anudeepND** [comment]
Wiki has been moved to readme.md for better visibility
