### ISSUE TITLE
Whitelist "api-iam.intercom.io"

### ISSUE THREAD

**Issue by lyrad87** [anudeepND/blacklist#87]
Hi,

I was wondering if you could whitelist "api-iam.intercom.io". It breaks the chat so it can't be used. It's a customer messaging platform and seems harmless. This is their website: [https://www.intercom.com/]( https://www.intercom.com/). If it's doing something I'm not aware of then please feel free to comment and close the ticket.

**Comment by scafroglia93** [comment]
+1

**Comment by anudeepND** [comment]
@lyrad87 Thanks for letting me know about the domain. It's removed in the latest update :)

**Comment by scafroglia93** [comment]
enjoy my donation :)
