### ISSUE TITLE
Embedded Tweet widgets being blocked

### ISSUE THREAD

**Issue by eugf** [anudeepND/blacklist#9]
This domain on your blacklist cdn.syndication.twimg.com seems to target the widgets used on sites to embed Tweets. 

For reference, this is the site I noticed it on 
http://www.iflscience.com/environment/truck-driver-ignored-signs-and-drove-across-perus-2000yearold-nasca-lines/

And I narrowed it down with the help of this forum
https://support.mozilla.org/en-US/questions/1189443?page=2
Specifically, this section
" This address should pop up a download dialog (no need to download):
https://cdn.syndication.twimg.com/tweets.json?callback=__twttr.callbacks.cb0&ids=950804340675088384&lang=en&suppress_response_codes=true&tz=GMT-0800 "

CDN is a Content Delivery Network, and as far as I can tell it seems to load images. Another domain I saw used it for shopping and keeping the pictures on their server rather than the store's own website. Here is the Wiki for reference
https://en.wikipedia.org/wiki/Content_delivery_network

Is there a history of abusing the Twitter CDN for ads? If not would it be possible to remove this from your blacklist?

**Comment by anudeepND** [comment]
@eugf Thanks for reporting :)
Removed both `syndication.twitter.com` and `cdn.syndication.twimg.com`

**Comment by eugf** [comment]
Thanks anudeepND!

In my testing of explicitly whitelisting ` cdn.syndication.twimg.com` and blacklisting `syndication.twitter.com` I got the Twitter widget to display, but not the other way around. 

Do you know what `syndication.twitter.com` does? A quick Google around shows that it may be a redirect for some kind of malware:
https://forums.malwarebytes.com/topic/198133-syndicationtwittercomijot-help/

**Comment by anudeepND** [comment]
I think it's kind of tracking domain, but it's not present in any other blacklist. I will add it again.

**Comment by eugf** [comment]
With your hint, I found these after filtering out all the malware results
https://blog.twitter.com/marketing/en_us/a/2015/promote-content-on-and-off-twitter-now-syndicating-promoted-tweets.html
https://blogs.wsj.com/cmo/2015/02/12/marketing-world-says-meh-to-twitters-ad-syndication-initiative/

Seems to be a paid ad service, which sounds like a Promoted ad on Google, except that it shows up off the Twitter platform in aggregated Twitter feeds. I would imagine something like a news site that shows the latest tweets.

Thanks for adding it back on! I think the community will benefit from this being on your blacklist.
