### ISSUE TITLE
xiaomi tracking (mint browser)

### ISSUE THREAD

**Issue by scafroglia93** [anudeepND/blacklist#94]
Source ->
https://www.youtube.com/watch?v=62kxZunBQyI&feature=emb_title

IoC ->
sa.api.intl.miui.com

need feedback for avoiding issue

**Comment by anudeepND** [comment]
Just read the news about it. Even though I have a Xiaomi device I have uninstalled their system app via adb commands. I will add the domain tomorrow

**Comment by anudeepND** [comment]
@scafroglia93 The domain was added long before the tracking was discovered. Closing
