### ISSUE TITLE
s3.tradingview.com

### ISSUE THREAD

**Issue by p1r473** [anudeepND/blacklist#97]
Hi, this domain hosts the images on tradingview.com and I believe it is a false positive

![image](https://user-images.githubusercontent.com/9235633/80926722-fa13be80-8d66-11ea-8f94-6d9fcb70b317.png)

**Comment by anudeepND** [comment]
@p1r473 Confirmed. Thanks for reporting.
Removed in https://github.com/anudeepND/blacklist/commit/9eeb31e89ae6df2ef1e0ca8706525d265d48c016
