### ISSUE TITLE
Suggestions for blacklist

### ISSUE THREAD

**Issue by specter78** [anudeepND/blacklist#98]
- geoapi.indiatimes.com
- geoapiet.indiatimes.com
- geo.thehindu.com
- firebaselogging-pa.googleapis.com
- test-app.link
- mobileads.indiatimes.com
- growthrx.in
- geoip.hotstar.com
- sitecheck.opera.com

**Comment by anudeepND** [comment]
@specter78 Can you provide some insights about these domains (like full URL, screenshots etc)? Are you using mobile apps for news sites such as  `indiatimes.com` and `thehindu.com`

**Comment by specter78** [comment]
I've been using these sites on both apps and browser and detected these domains through DNS logs. I had these domains blocked for >2 weeks and haven't come across any issue.

**Comment by specter78** [comment]
>Can you provide some insights about these domains (like full URL, screenshots etc)?

Don't have these.

> Are you using mobile apps for news sites such as indiatimes.com and thehindu.com

I've been using these sites on both apps and browser and detected these domains through DNS logs. I had these domains blocked for >2 weeks and haven't come across any issue.

**Comment by anudeepND** [comment]
@anudeepND Okay. I have added growthrx.com and firebaselogging-pa.googleapis.com in https://github.com/anudeepND/blacklist/commit/55424d24d37ae53bc0af2adc7e1ad7ffb7ac71b6. `*.app.link` is used as a link to open the website content on the native app if it's installed, so blocking this may cause problem to many users

**Comment by specter78** [comment]
> Okay. I have added growthrx.com and firebaselogging-pa.googleapis.com in [55424d2](https://github.com/anudeepND/blacklist/commit/55424d24d37ae53bc0af2adc7e1ad7ffb7ac71b6). `*.app.link` is used as a link to open the website content on the native app if it's installed, so blocking this may cause problem to many users

You added `firebaselogging.googleapis.com` and not `firebaselogging-pa.googleapis.com`, though first one is also required.
