### ISSUE TITLE
suggestion - sjv.io

### ISSUE THREAD

**Issue by git-anish** [anudeepND/blacklist#99]
Hey,

services like http://refurb-tracker.com/ and Aeroplan.ca affiliate links use sjv.io - specifically apple.sjv.io

I think this domain should be unblocked from the list due to it being an affiliate link rather than a adserver or tracker

It breaks fairly useful services

thoughts on removing it from your list?

Regards,

Anish S

**Comment by anudeepND** [comment]
@git-anish Thanks for reporting. I have removed them in the latest update. However they perform pixel tracking but I don't have anything to test it
